//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CAAnimationDelegate-Protocol.h"

@class UIColor;

@interface _TtC8Stickers11ProgressBar : UIView <CAAnimationDelegate>
{
    // Error parsing type: , name: animation
    // Error parsing type: , name: animationDidStart
    // Error parsing type: , name: timerDuration
    // Error parsing type: , name: defaultColor
    // Error parsing type: , name: defaultBackgroundColor
    // Error parsing type: , name: fgProgressLayer.storage
    // Error parsing type: , name: bgProgressLayer.storage
    // Error parsing type: , name: timer.storage
    // Error parsing type: , name: shouldAnimate
    // Error parsing type: , name: timeType
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (void)updateTimer;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, retain) UIColor *defaultBackgroundColor; // @synthesize defaultBackgroundColor;
@property(nonatomic, retain) UIColor *defaultColor; // @synthesize defaultColor;

@end

