//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers26BasePurchaseViewController.h"

@class UILabel, _TtC8Stickers10BaseButton, _TtC8Stickers11ProgressBar, _TtC8Stickers14UICustomButton;

@interface _TtC8Stickers22PurchaseViewController : _TtC8Stickers26BasePurchaseViewController
{
    // Error parsing type: , name: startButton
    // Error parsing type: , name: freeTrialLabel
    // Error parsing type: , name: priceLabel
    // Error parsing type: , name: restoreButton
    // Error parsing type: , name: moreOptionsButton
    // Error parsing type: , name: timerLabel
    // Error parsing type: , name: progressBar
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onApplicationDidBecomeActiveWithNotification:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak _TtC8Stickers11ProgressBar *progressBar; // @synthesize progressBar;
@property(nonatomic) __weak UILabel *timerLabel; // @synthesize timerLabel;
@property(nonatomic) __weak _TtC8Stickers10BaseButton *moreOptionsButton; // @synthesize moreOptionsButton;
@property(nonatomic) __weak _TtC8Stickers10BaseButton *restoreButton; // @synthesize restoreButton;
@property(nonatomic) __weak UILabel *priceLabel; // @synthesize priceLabel;
@property(nonatomic) __weak UILabel *freeTrialLabel; // @synthesize freeTrialLabel;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *startButton; // @synthesize startButton;

@end

