//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC8Stickers7Sticker : NSObject
{
    // Error parsing type: , name: id
    // Error parsing type: , name: categoryDescription
    // Error parsing type: , name: categoryID
    // Error parsing type: , name: stickerIconFile
    // Error parsing type: , name: animatedStickerIconFile
    // Error parsing type: , name: whatsAppIconFile
    // Error parsing type: , name: localFileURL
    // Error parsing type: , name: localIdentifier
    // Error parsing type: , name: editorLocalFilename
    // Error parsing type: , name: status
    // Error parsing type: , name: order
    // Error parsing type: , name: messageDownloadStatus
    // Error parsing type: , name: libraryDownloadStatus
    // Error parsing type: , name: whatsappDownloadStatus
    // Error parsing type: , name: favoriteDownloadStatus
    // Error parsing type: , name: totalDownloads
    // Error parsing type: , name: createdAt
    // Error parsing type: , name: updatedAt
    // Error parsing type: , name: lastUpload
    // Error parsing type: , name: originalCategoryID
    // Error parsing type: , name: originalStickerID
    // Error parsing type: , name: groups
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSString *originalStickerID; // @synthesize originalStickerID;
@property(nonatomic, copy) NSString *originalCategoryID; // @synthesize originalCategoryID;
@property(nonatomic) long long lastUpload; // @synthesize lastUpload;
@property(nonatomic) long long updatedAt; // @synthesize updatedAt;
@property(nonatomic) long long createdAt; // @synthesize createdAt;
@property(nonatomic) long long totalDownloads; // @synthesize totalDownloads;
@property(nonatomic) long long favoriteDownloadStatus; // @synthesize favoriteDownloadStatus;
@property(nonatomic) long long whatsappDownloadStatus; // @synthesize whatsappDownloadStatus;
@property(nonatomic) long long libraryDownloadStatus; // @synthesize libraryDownloadStatus;
@property(nonatomic) long long messageDownloadStatus; // @synthesize messageDownloadStatus;
@property(nonatomic) long long order; // @synthesize order;
@property(nonatomic) long long status; // @synthesize status;
@property(nonatomic, copy) NSString *editorLocalFilename; // @synthesize editorLocalFilename;
@property(nonatomic, copy) NSString *localIdentifier; // @synthesize localIdentifier;
@property(nonatomic, copy) NSString *localFileURL; // @synthesize localFileURL;
@property(nonatomic, copy) NSString *whatsAppIconFile; // @synthesize whatsAppIconFile;
@property(nonatomic, copy) NSString *animatedStickerIconFile; // @synthesize animatedStickerIconFile;
@property(nonatomic, copy) NSString *stickerIconFile; // @synthesize stickerIconFile;
@property(nonatomic, copy) NSString *categoryID; // @synthesize categoryID;
@property(nonatomic, copy) NSString *categoryDescription; // @synthesize categoryDescription;
@property(nonatomic, copy) NSString *id; // @synthesize id;

@end

