//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Stickers13PaywallConfig : _TtCs12_SwiftObject
{
    // Error parsing type: , name: isFreeStickerPack
    // Error parsing type: , name: closeButtonStartVisible
    // Error parsing type: , name: canShowCloseButton
    // Error parsing type: , name: customTitle
    // Error parsing type: , name: customAttributedTitle
    // Error parsing type: , name: customImage
    // Error parsing type: , name: customDescription
    // Error parsing type: , name: customPrice
    // Error parsing type: , name: customButtonTitle
    // Error parsing type: , name: showSeeFreePacksButton
    // Error parsing type: , name: hoursToUnlockStickerMaker
}

@end

