//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UILabel, UISlider, UIStackView, _TtC8Stickers17UISubtitledButton;

@interface _TtC8Stickers25EditorToolsViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: eraserButton
    // Error parsing type: , name: magicEraserButton
    // Error parsing type: , name: restoreButton
    // Error parsing type: , name: thicknessSlider
    // Error parsing type: , name: buttonsStackView
    // Error parsing type: , name: eraserTitleLabel
    // Error parsing type: , name: radioButtonsController
    // Error parsing type: , name: eraseTheBackgroundTitle
    // Error parsing type: , name: eraserThicknessTitle
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onThicknessSlider:(id)arg1;
- (void)onRestoreButton:(id)arg1;
- (void)onMagicEraserButton:(id)arg1;
- (void)onEraserButton:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UILabel *eraserTitleLabel; // @synthesize eraserTitleLabel;
@property(nonatomic) __weak UIStackView *buttonsStackView; // @synthesize buttonsStackView;
@property(nonatomic) __weak UISlider *thicknessSlider; // @synthesize thicknessSlider;
@property(nonatomic) __weak _TtC8Stickers17UISubtitledButton *restoreButton; // @synthesize restoreButton;
@property(nonatomic) __weak _TtC8Stickers17UISubtitledButton *magicEraserButton; // @synthesize magicEraserButton;
@property(nonatomic) __weak _TtC8Stickers17UISubtitledButton *eraserButton; // @synthesize eraserButton;

@end

