//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIColor;

@interface _TtC8Stickers11LabelSwitch : UIView
{
    // Error parsing type: , name: circleView.storage
    // Error parsing type: , name: leftPart.storage
    // Error parsing type: , name: rightPart.storage
    // Error parsing type: , name: switchConfigL
    // Error parsing type: , name: switchConfigR
    // Error parsing type: , name: edge
    // Error parsing type: , name: circlePadding
    // Error parsing type: , name: minimumSize
    // Error parsing type: , name: stateL
    // Error parsing type: , name: stateR
    // Error parsing type: , name: fullSizeTapGesture
    // Error parsing type: , name: delegate
    // Error parsing type: , name: curState
    // Error parsing type: , name: circleShadow
    // Error parsing type: , name: circleColor
    // Error parsing type: , name: fullSizeTapEnabled
    // Error parsing type: , name: calculatedSize
    // Error parsing type: , name: lBackColor
    // Error parsing type: , name: rBackColor
    // Error parsing type: , name: lTextColor
    // Error parsing type: , name: rTextColor
    // Error parsing type: , name: lText
    // Error parsing type: , name: rText
    // Error parsing type: , name: fontSize
    // Error parsing type: , name: widthLayout
    // Error parsing type: , name: heightLayout
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) double fontSize; // @synthesize fontSize;
@property(nonatomic, copy) NSString *rText; // @synthesize rText;
@property(nonatomic, copy) NSString *lText; // @synthesize lText;
@property(nonatomic, retain) UIColor *rTextColor; // @synthesize rTextColor;
@property(nonatomic, retain) UIColor *lTextColor; // @synthesize lTextColor;
@property(nonatomic, retain) UIColor *rBackColor; // @synthesize rBackColor;
@property(nonatomic, retain) UIColor *lBackColor; // @synthesize lBackColor;
- (void)switchTapedWithSender:(id)arg1;

@end

