//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class NSLayoutConstraint, UIButton, UICollectionView, UIImageView, UIView, _TtC8Stickers11LabelSwitch, _TtC8Stickers14DailyTextField, _TtC8Stickers14DownloadButton;

@interface _TtC8Stickers28NewStickerPackViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: backButton
    // Error parsing type: , name: downloadButton
    // Error parsing type: , name: downloadAllButton
    // Error parsing type: , name: coverImageView
    // Error parsing type: , name: nameTextField
    // Error parsing type: , name: downloadButtonHeightLayoutConstraint
    // Error parsing type: , name: stickerContainerView
    // Error parsing type: , name: descriptionTextField
    // Error parsing type: , name: labelSwitch
    // Error parsing type: , name: nameTextFieldLeadingToSuperviewLayoutConstraint
    // Error parsing type: , name: nameTextFieldLeadingToCoverLayoutConstraint
    // Error parsing type: , name: picker
    // Error parsing type: , name: identifier
    // Error parsing type: , name: kMinimumPixels
    // Error parsing type: , name: minimumInteritemSpacing
    // Error parsing type: , name: minimumLineSpacingPacks
    // Error parsing type: , name: packsPerRow
    // Error parsing type: , name: coverHasChanged
    // Error parsing type: , name: stickers
    // Error parsing type: , name: currentImagePurpose
    // Error parsing type: , name: currentEditedStickerIndex
    // Error parsing type: , name: needUpdateAllPack
    // Error parsing type: , name: backButtonVisible
    // Error parsing type: , name: user
    // Error parsing type: , name: category
    // Error parsing type: , name: isAddingSticker
    // Error parsing type: , name: mustShowLibrary
    // Error parsing type: , name: stickerToAdd
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onDownloadAllButton:(id)arg1;
- (void)onDownloadButton:(id)arg1;
- (void)on3DotsButton:(id)arg1;
- (void)onBackButton:(id)arg1;
- (void)onLabelSwitchTapGesture;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;
@property(nonatomic) __weak NSLayoutConstraint *nameTextFieldLeadingToCoverLayoutConstraint; // @synthesize nameTextFieldLeadingToCoverLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *nameTextFieldLeadingToSuperviewLayoutConstraint; // @synthesize nameTextFieldLeadingToSuperviewLayoutConstraint;
@property(nonatomic) __weak _TtC8Stickers11LabelSwitch *labelSwitch; // @synthesize labelSwitch;
@property(nonatomic) __weak _TtC8Stickers14DailyTextField *descriptionTextField; // @synthesize descriptionTextField;
@property(nonatomic) __weak UIView *stickerContainerView; // @synthesize stickerContainerView;
@property(nonatomic) __weak NSLayoutConstraint *downloadButtonHeightLayoutConstraint; // @synthesize downloadButtonHeightLayoutConstraint;
@property(nonatomic) __weak _TtC8Stickers14DailyTextField *nameTextField; // @synthesize nameTextField;
@property(nonatomic) __weak UIImageView *coverImageView; // @synthesize coverImageView;
@property(nonatomic) __weak UIButton *downloadAllButton; // @synthesize downloadAllButton;
@property(nonatomic) __weak _TtC8Stickers14DownloadButton *downloadButton; // @synthesize downloadButton;
@property(nonatomic) __weak UIButton *backButton; // @synthesize backButton;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

