//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UIImageView, UILabel, UIStackView, UIView, _TtC8Stickers14UICustomButton;

@interface _TtC8Stickers21MyPacksViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: stackVew
    // Error parsing type: , name: createdPacksContainerView
    // Error parsing type: , name: favoriteContainerView
    // Error parsing type: , name: downloadedContainerView
    // Error parsing type: , name: choosePhotoButton
    // Error parsing type: , name: editProfileNameButton
    // Error parsing type: , name: userNameLabel
    // Error parsing type: , name: profileImageView
    // Error parsing type: , name: createdPacksPackCarouselView
    // Error parsing type: , name: favoritePackCarouselView
    // Error parsing type: , name: downloadedPackCarouselView
    // Error parsing type: , name: downloadedPacks
    // Error parsing type: , name: favoritePacks
    // Error parsing type: , name: user
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onEditProfileNameButton:(id)arg1;
- (void)onChoosePhotoButton:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)onReceivedUserNotification:(id)arg1;
- (void)onReceivedUserStickersNotification:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UIImageView *profileImageView; // @synthesize profileImageView;
@property(nonatomic) __weak UILabel *userNameLabel; // @synthesize userNameLabel;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *editProfileNameButton; // @synthesize editProfileNameButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *choosePhotoButton; // @synthesize choosePhotoButton;
@property(nonatomic) __weak UIView *downloadedContainerView; // @synthesize downloadedContainerView;
@property(nonatomic) __weak UIView *favoriteContainerView; // @synthesize favoriteContainerView;
@property(nonatomic) __weak UIView *createdPacksContainerView; // @synthesize createdPacksContainerView;
@property(nonatomic) __weak UIStackView *stackVew; // @synthesize stackVew;

@end

