//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC8Stickers18CropViewController : UIViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: image
    // Error parsing type: , name: keepAspectRatio
    // Error parsing type: , name: cropAspectRatio
    // Error parsing type: , name: cropRect
    // Error parsing type: , name: imageCropRect
    // Error parsing type: , name: toolbarHidden
    // Error parsing type: , name: rotationEnabled
    // Error parsing type: , name: cropView
}

- (void).cxx_destruct;
- (void)constrain:(id)arg1;
- (void)done:(id)arg1;
- (void)cancel:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;

@end

