//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UICollectionView, UISearchBar;

@interface _TtC8Stickers27StickerSearchViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: searchBar
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: stickers
    // Error parsing type: , name: allStickers
    // Error parsing type: , name: searchTimer
    // Error parsing type: , name: searchDelay
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onSearchTimer;
- (void)viewDidLoad;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UISearchBar *searchBar; // @synthesize searchBar;

@end

