//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8Stickers9SaveEvent : NSObject
{
    // Error parsing type: , name: object
    // Error parsing type: , name: action
    // Error parsing type: , name: destination
    // Error parsing type: , name: shouldLog
    // Error parsing type: , name: fromView
    // Error parsing type: , name: headerView
    // Error parsing type: , name: existingStickerImageDicts
    // Error parsing type: , name: stickersDownloadDataArray
    // Error parsing type: , name: stickerLocationDicts
    // Error parsing type: , name: successOrFailure
    // Error parsing type: , name: error
    // Error parsing type: , name: favoritePack
}

- (void).cxx_destruct;
- (id)init;

@end

