//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC8Stickers11WDFlashCard : UIView
{
    // Error parsing type: , name: animationInProgress
    // Error parsing type: , name: tapToFlipGesture
    // Error parsing type: , name: flipAnimation
    // Error parsing type: , name: duration
    // Error parsing type: , name: showFront
    // Error parsing type: , name: disableTouchToFlipFesture
    // Error parsing type: , name: flashCardDelegate
    // Error parsing type: , name: frontView
    // Error parsing type: , name: backView
}

- (void).cxx_destruct;
- (void)flip;
- (void)showBackView;
- (void)showFrontView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

