//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8StickersP33_B9D0F84B0B3F8BD387CCD4AF99CB8E7315LabelSwitchPart : _TtCs12_SwiftObject
{
    // Error parsing type: , name: label
    // Error parsing type: , name: back
    // Error parsing type: , name: mask.storage
}

@end

