//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UIColor;

@interface _TtC8Stickers26ScrollableSegmentedControl : UIControl
{
    // Error parsing type: , name: flowLayout
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: collectionViewController
    // Error parsing type: , name: segmentsData
    // Error parsing type: , name: longestTextWidth
    // Error parsing type: , name: fixedSegmentWidth
    // Error parsing type: , name: segmentStyle
    // Error parsing type: , name: _segmentContentColor
    // Error parsing type: , name: _underlineHeight
    // Error parsing type: , name: _selectedSegmentContentColor
    // Error parsing type: , name: _selectedSegmentBackgroundColor
    // Error parsing type: , name: normalAttributes
    // Error parsing type: , name: highlightedAttributes
    // Error parsing type: , name: selectedAttributes
    // Error parsing type: , name: _titleAttributes
    // Error parsing type: , name: selectedSegmentIndex
    // Error parsing type: , name: underlineSelected
}

- (void).cxx_destruct;
- (void)layoutSubviews;
@property(nonatomic) _Bool underlineSelected; // @synthesize underlineSelected;
@property(nonatomic) long long selectedSegmentIndex; // @synthesize selectedSegmentIndex;
- (id)titleForSegmentAt:(long long)arg1;
@property(nonatomic, readonly) long long numberOfSegments;
- (void)removeSegmentAt:(long long)arg1;
- (void)insertSegmentWithTitle:(id)arg1 image:(id)arg2 at:(long long)arg3;
- (void)insertSegmentWith:(id)arg1 at:(long long)arg2;
- (void)insertSegmentWithTitle:(id)arg1 at:(long long)arg2;
- (id)titleTextAttributesFor:(unsigned long long)arg1;
- (void)setTitleTextAttributes:(id)arg1 for:(unsigned long long)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) UIColor *selectedSegmentBackgroundColor;
@property(nonatomic, retain) UIColor *selectedSegmentContentColor;
@property(nonatomic) double underlineHeight;
@property(nonatomic, retain) UIColor *segmentContentColor;
@property(nonatomic, retain) UIColor *tintColor;
@property(nonatomic) long long segmentStyle; // @synthesize segmentStyle;

@end

