//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers33BaseStickerPackCollectionViewCell.h"

@class UIImageView, UILabel, _TtC8Stickers12UICustomView, _TtC8Stickers14UICustomButton;

@interface _TtC8Stickers27DailyPackCollectionViewCell : _TtC8Stickers33BaseStickerPackCollectionViewCell
{
    // Error parsing type: , name: timeLabel
    // Error parsing type: , name: clockImageView
    // Error parsing type: , name: getButton
    // Error parsing type: , name: nextInLabel
    // Error parsing type: , name: nextInView
    // Error parsing type: , name: stickerImageView
    // Error parsing type: , name: delegate
    // Error parsing type: , name: type
    // Error parsing type: , name: cellUpdateTimer
    // Error parsing type: , name: secondsLeft
    // Error parsing type: , name: viewTapGesture
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)onCellUpdateTimer;
- (void)onGetButton:(id)arg1;
- (void)onCellTapGesture:(id)arg1;
- (void)prepareForReuse;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *stickerImageView; // @synthesize stickerImageView;
@property(nonatomic) __weak _TtC8Stickers12UICustomView *nextInView; // @synthesize nextInView;
@property(nonatomic) __weak UILabel *nextInLabel; // @synthesize nextInLabel;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *getButton; // @synthesize getButton;
@property(nonatomic) __weak UIImageView *clockImageView; // @synthesize clockImageView;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel;

@end

