//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, _TtC8Stickers18PackCollectionView;

@interface _TtC8Stickers26LabeledStickerCarouselView : UIView
{
    // Error parsing type: , name: contentView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: allLabel
    // Error parsing type: , name: emptyCollectionLabel
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: leftContainerView
    // Error parsing type: , name: stickers
    // Error parsing type: , name: emptyMessage
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak UIView *leftContainerView; // @synthesize leftContainerView;
@property(nonatomic) __weak _TtC8Stickers18PackCollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UILabel *emptyCollectionLabel; // @synthesize emptyCollectionLabel;
@property(nonatomic) __weak UILabel *allLabel; // @synthesize allLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView;

@end

