//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Stickers22RemoteCategoryDownload : _TtCs12_SwiftObject
{
    // Error parsing type: , name: id
    // Error parsing type: , name: library
    // Error parsing type: , name: message
    // Error parsing type: , name: whatsapp
    // Error parsing type: , name: createdAt
    // Error parsing type: , name: updatedAt
}

@end

