//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class _TtC8Stickers12UICustomView;

@interface _TtC8Stickers12ThankYouView : UIView
{
    // Error parsing type: , name: contentView
    // Error parsing type: , name: customView
    // Error parsing type: , name: onDismiss
}

- (void).cxx_destruct;
- (void)onTapGesture;
- (void)onCloseButton:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak _TtC8Stickers12UICustomView *customView; // @synthesize customView;
@property(nonatomic, retain) UIView *contentView; // @synthesize contentView;

@end

