//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface _TtC8Stickers12UICustomView : UIView
{
    // Error parsing type: , name: rotation
    // Error parsing type: , name: circle
    // Error parsing type: , name: roundedCorner
    // Error parsing type: , name: dashedBorder
    // Error parsing type: , name: cornerRadius
    // Error parsing type: , name: maskToBounds
    // Error parsing type: , name: borderWidth
    // Error parsing type: , name: borderColor
    // Error parsing type: , name: shadowAround
    // Error parsing type: , name: shadowOffset
    // Error parsing type: , name: shadowOpacity
    // Error parsing type: , name: shadowRadius
    // Error parsing type: , name: shadowColor
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)prepareForInterfaceBuilder;
@property(nonatomic, retain) UIColor *shadowColor; // @synthesize shadowColor;
@property(nonatomic) double shadowRadius; // @synthesize shadowRadius;
@property(nonatomic) float shadowOpacity; // @synthesize shadowOpacity;
@property(nonatomic) struct CGSize shadowOffset; // @synthesize shadowOffset;
@property(nonatomic) _Bool shadowAround; // @synthesize shadowAround;
@property(nonatomic, retain) UIColor *borderColor; // @synthesize borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(nonatomic) _Bool maskToBounds; // @synthesize maskToBounds;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius;
@property(nonatomic) _Bool dashedBorder; // @synthesize dashedBorder;
@property(nonatomic) _Bool roundedCorner; // @synthesize roundedCorner;
@property(nonatomic) _Bool circle; // @synthesize circle;
@property(nonatomic) double rotation; // @synthesize rotation;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

