//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UICollectionView, UIScrollView, _TtC8Stickers14UICustomButton;

@interface _TtC8Stickers26EditorExtrasViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: addTextButton
    // Error parsing type: , name: glassesButton
    // Error parsing type: , name: hatsButton
    // Error parsing type: , name: cuteFacesButton
    // Error parsing type: , name: hairButton
    // Error parsing type: , name: eyesButton
    // Error parsing type: , name: mouthsButton
    // Error parsing type: , name: laughtsButton
    // Error parsing type: , name: beardsButton
    // Error parsing type: , name: armsButton
    // Error parsing type: , name: iconsButton
    // Error parsing type: , name: chatsButton
    // Error parsing type: , name: comicsButton
    // Error parsing type: , name: halloweenButton
    // Error parsing type: , name: memesButton
    // Error parsing type: , name: accessoryButtonsScrollView
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: radioButtonsController
    // Error parsing type: , name: buttons.storage
    // Error parsing type: , name: buttonImages
    // Error parsing type: , name: stickers
    // Error parsing type: , name: packStickers
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onAccessoryButton:(id)arg1;
- (void)onAddTextButton:(id)arg1;
- (void)onContentWasPutInMemoryWithNotification:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UIScrollView *accessoryButtonsScrollView; // @synthesize accessoryButtonsScrollView;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *memesButton; // @synthesize memesButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *halloweenButton; // @synthesize halloweenButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *comicsButton; // @synthesize comicsButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *chatsButton; // @synthesize chatsButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *iconsButton; // @synthesize iconsButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *armsButton; // @synthesize armsButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *beardsButton; // @synthesize beardsButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *laughtsButton; // @synthesize laughtsButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *mouthsButton; // @synthesize mouthsButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *eyesButton; // @synthesize eyesButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *hairButton; // @synthesize hairButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *cuteFacesButton; // @synthesize cuteFacesButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *hatsButton; // @synthesize hatsButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *glassesButton; // @synthesize glassesButton;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *addTextButton; // @synthesize addTextButton;

@end

