//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers14UICustomButton.h"

@class UIColor, UIImage;

@interface _TtC8Stickers12SelectButton : _TtC8Stickers14UICustomButton
{
    // Error parsing type: , name: buttonState
    // Error parsing type: , name: normalBorderColor
    // Error parsing type: , name: normalTitleColor
    // Error parsing type: , name: normalBackgroundColor
    // Error parsing type: , name: normalImage
    // Error parsing type: , name: selectedBorderColor
    // Error parsing type: , name: selectedTitleColor
    // Error parsing type: , name: selectedBackgroundColor
    // Error parsing type: , name: selectedImage
}

- (void).cxx_destruct;
- (void)prepareForInterfaceBuilder;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) UIImage *selectedImage; // @synthesize selectedImage;
@property(nonatomic, retain) UIColor *selectedBackgroundColor; // @synthesize selectedBackgroundColor;
@property(nonatomic, retain) UIColor *selectedTitleColor; // @synthesize selectedTitleColor;
@property(nonatomic, retain) UIColor *selectedBorderColor; // @synthesize selectedBorderColor;
@property(nonatomic, retain) UIImage *normalImage; // @synthesize normalImage;
@property(nonatomic, retain) UIColor *normalBackgroundColor; // @synthesize normalBackgroundColor;
@property(nonatomic, retain) UIColor *normalTitleColor; // @synthesize normalTitleColor;
@property(nonatomic, retain) UIColor *normalBorderColor; // @synthesize normalBorderColor;
@property(nonatomic) long long buttonState; // @synthesize buttonState;

@end

