//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIColor;

@interface _TtCC8Stickers26ScrollableSegmentedControlP33_BBFC12BAAA4C960ACF4034D51EEDD4AE29BaseSegmentCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: underlineView
    // Error parsing type: , name: underlineHeight
    // Error parsing type: , name: contentColor
    // Error parsing type: , name: selectedContentColor
    // Error parsing type: , name: selectedBackgroundColor
    // Error parsing type: , name: normalAttributedTitle
    // Error parsing type: , name: highlightedAttributedTitle
    // Error parsing type: , name: selectedAttributedTitle
    // Error parsing type: , name: variableConstraints
    // Error parsing type: , name: showUnderline
}

- (void).cxx_destruct;
@property(nonatomic) _Bool selected;
- (_Bool)isSelected;
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;
- (void)setNeedsUpdateConstraints;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) UIColor *tintColor;

@end

