//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers14UICustomButton.h"

@interface _TtC8Stickers14DownloadButton : _TtC8Stickers14UICustomButton
{
    // Error parsing type: , name: currentAction
    // Error parsing type: , name: type
    // Error parsing type: , name: sticker
    // Error parsing type: , name: stickerPack
}

- (void).cxx_destruct;
- (void)onFavoritedStickerNotification:(id)arg1;
- (void)onDownloadedStickerPack:(id)arg1;
- (void)onUpdatedDefaultDownloadDestination:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

