//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UIButton, UITextView, UIView, _TtC8Stickers18UIImageViewLoading;

@interface _TtC8Stickers26BasePurchaseViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: quitButton
    // Error parsing type: , name: loaderView
    // Error parsing type: , name: loaderImage
    // Error parsing type: , name: infoTextView
    // Error parsing type: , name: config
    // Error parsing type: , name: purchaseManager
    // Error parsing type: , name: identifier
    // Error parsing type: , name: privacyPolicyLink
    // Error parsing type: , name: termsOfUseLink
    // Error parsing type: , name: restoreLink
    // Error parsing type: , name: mainProductTask
    // Error parsing type: , name: productsTimer
    // Error parsing type: , name: isShowingInterstitial
    // Error parsing type: , name: onDismiss
    // Error parsing type: , name: onClose
    // Error parsing type: , name: onComplete
    // Error parsing type: , name: shouldRequestReviewWhenClosed
    // Error parsing type: , name: closeButtonStartVisible
    // Error parsing type: , name: canShowCloseButton
    // Error parsing type: , name: onViewWillDisappear
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onQuitButton:(id)arg1;
- (void)remoteConfigsWereChangedWithNotification:(id)arg1;
- (void)onIapProductArrivalWithNotification:(id)arg1;
- (void)onStartButton:(id)arg1;
- (void)onMoreOptionsButton:(id)arg1;
- (void)onRestoreButton:(id)arg1;
- (void)onProductsTimer;
- (void)onApplicationDidBecomeActiveWithNotification:(id)arg1;
- (void)onFastReviewWithNotification:(id)arg1;
- (void)onAskForAppRateNotificationWithNotification:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;
@property(nonatomic) __weak UITextView *infoTextView; // @synthesize infoTextView;
@property(nonatomic) __weak _TtC8Stickers18UIImageViewLoading *loaderImage; // @synthesize loaderImage;
@property(nonatomic) __weak UIView *loaderView; // @synthesize loaderView;
@property(nonatomic) __weak UIButton *quitButton; // @synthesize quitButton;

@end

