//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC8Stickers12CropRectView : UIView
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: showsGridMajor
    // Error parsing type: , name: showsGridMinor
    // Error parsing type: , name: keepAspectRatio
    // Error parsing type: , name: resizeImageView
    // Error parsing type: , name: topLeftCornerView
    // Error parsing type: , name: topRightCornerView
    // Error parsing type: , name: bottomLeftCornerView
    // Error parsing type: , name: bottomRightCornerView
    // Error parsing type: , name: topEdgeView
    // Error parsing type: , name: leftEdgeView
    // Error parsing type: , name: rightEdgeView
    // Error parsing type: , name: bottomEdgeView
    // Error parsing type: , name: initialRect
    // Error parsing type: , name: fixedAspectRatio
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

