//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@interface _TtC8Stickers8Category : NSObject <NSCoding>
{
    // Error parsing type: , name: id
    // Error parsing type: , name: title
    // Error parsing type: , name: iconName
    // Error parsing type: , name: stickers
}

- (void).cxx_destruct;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

