//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UICollectionView;

@interface _TtC8Stickers22StickersViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: stickerPack
    // Error parsing type: , name: stickers
    // Error parsing type: , name: task
    // Error parsing type: , name: delegate
    // Error parsing type: , name: lineSpacing.storage
    // Error parsing type: , name: cellSpacing.storage
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onReloadStickersNotificationWithNotification:(id)arg1;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

