//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers26BasePurchaseViewController.h"

@class NSLayoutConstraint, UIImageView, UILabel, UIStackView, _TtC8Stickers10BaseButton, _TtC8Stickers11WDFlashCard, _TtC8Stickers12UICustomView, _TtC8Stickers14UICustomButton;

@interface _TtC8Stickers28CustomPurchaseViewController : _TtC8Stickers26BasePurchaseViewController
{
    // Error parsing type: , name: startButton
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: imageView
    // Error parsing type: , name: descriptionLabel
    // Error parsing type: , name: priceLabel
    // Error parsing type: , name: moreSignUpOptionsButton
    // Error parsing type: , name: seeFreePacksButton
    // Error parsing type: , name: orLabel
    // Error parsing type: , name: flashCardView
    // Error parsing type: , name: firstView
    // Error parsing type: , name: secondView
    // Error parsing type: , name: screen2QuitButton
    // Error parsing type: , name: screen2BackToFreeTrialButton
    // Error parsing type: , name: screen2JoinNowLabel
    // Error parsing type: , name: screen2MessageLabel
    // Error parsing type: , name: screen2BestValueLabel
    // Error parsing type: , name: screen2YearLabel
    // Error parsing type: , name: screen2MonthLabel
    // Error parsing type: , name: screen2WeekLabel
    // Error parsing type: , name: screen2YearPriceLabel
    // Error parsing type: , name: screen2MonthPriceLabel
    // Error parsing type: , name: screen2WeekPriceLabel
    // Error parsing type: , name: screen2YearAverageLabel
    // Error parsing type: , name: screen2MonthAverageLabel
    // Error parsing type: , name: screen2WeekAverageLabel
    // Error parsing type: , name: screen2WeekStackView
    // Error parsing type: , name: infoTextViewTopLayoutConstraint
    // Error parsing type: , name: infoTextViewHeightLayoutConstraint
    // Error parsing type: , name: infoTextViewBottomLayoutConstraint
    // Error parsing type: , name: customAttributedTitle
    // Error parsing type: , name: customImageName
    // Error parsing type: , name: customButtonTitle
    // Error parsing type: , name: customDescription
    // Error parsing type: , name: showSeeFreePacksButton
    // Error parsing type: , name: longFrequencyAvgPrice
    // Error parsing type: , name: mediumFrequencyAvgPrice
    // Error parsing type: , name: shortFrequencyAvgPrice
    // Error parsing type: , name: viewScale
    // Error parsing type: , name: viewAlpha
    // Error parsing type: , name: type
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onWeeklyButton:(id)arg1;
- (void)onMonthlyButton:(id)arg1;
- (void)onYearlyButton:(id)arg1;
- (void)onMoreOptionsButton:(id)arg1;
- (void)onBackToFreeTrialButton:(id)arg1;
- (void)onSeeFreePackButton:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak NSLayoutConstraint *infoTextViewBottomLayoutConstraint; // @synthesize infoTextViewBottomLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *infoTextViewHeightLayoutConstraint; // @synthesize infoTextViewHeightLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *infoTextViewTopLayoutConstraint; // @synthesize infoTextViewTopLayoutConstraint;
@property(nonatomic) __weak UIStackView *screen2WeekStackView; // @synthesize screen2WeekStackView;
@property(nonatomic) __weak UILabel *screen2WeekAverageLabel; // @synthesize screen2WeekAverageLabel;
@property(nonatomic) __weak UILabel *screen2MonthAverageLabel; // @synthesize screen2MonthAverageLabel;
@property(nonatomic) __weak UILabel *screen2YearAverageLabel; // @synthesize screen2YearAverageLabel;
@property(nonatomic) __weak UILabel *screen2WeekPriceLabel; // @synthesize screen2WeekPriceLabel;
@property(nonatomic) __weak UILabel *screen2MonthPriceLabel; // @synthesize screen2MonthPriceLabel;
@property(nonatomic) __weak UILabel *screen2YearPriceLabel; // @synthesize screen2YearPriceLabel;
@property(nonatomic) __weak UILabel *screen2WeekLabel; // @synthesize screen2WeekLabel;
@property(nonatomic) __weak UILabel *screen2MonthLabel; // @synthesize screen2MonthLabel;
@property(nonatomic) __weak UILabel *screen2YearLabel; // @synthesize screen2YearLabel;
@property(nonatomic) __weak UILabel *screen2BestValueLabel; // @synthesize screen2BestValueLabel;
@property(nonatomic) __weak UILabel *screen2MessageLabel; // @synthesize screen2MessageLabel;
@property(nonatomic) __weak UILabel *screen2JoinNowLabel; // @synthesize screen2JoinNowLabel;
@property(nonatomic) __weak _TtC8Stickers10BaseButton *screen2BackToFreeTrialButton; // @synthesize screen2BackToFreeTrialButton;
@property(nonatomic) __weak _TtC8Stickers10BaseButton *screen2QuitButton; // @synthesize screen2QuitButton;
@property(nonatomic) __weak _TtC8Stickers12UICustomView *secondView; // @synthesize secondView;
@property(nonatomic) __weak _TtC8Stickers12UICustomView *firstView; // @synthesize firstView;
@property(nonatomic) __weak _TtC8Stickers11WDFlashCard *flashCardView; // @synthesize flashCardView;
@property(nonatomic) __weak UILabel *orLabel; // @synthesize orLabel;
@property(nonatomic) __weak _TtC8Stickers10BaseButton *seeFreePacksButton; // @synthesize seeFreePacksButton;
@property(nonatomic) __weak _TtC8Stickers10BaseButton *moreSignUpOptionsButton; // @synthesize moreSignUpOptionsButton;
@property(nonatomic) __weak UILabel *priceLabel; // @synthesize priceLabel;
@property(nonatomic) __weak UILabel *descriptionLabel; // @synthesize descriptionLabel;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *startButton; // @synthesize startButton;

@end

