//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8Stickers11SpinnerTask : NSObject
{
    // Error parsing type: , name: tag
    // Error parsing type: , name: taskEnded
    // Error parsing type: , name: loadingViewStarted
    // Error parsing type: , name: loadingViewEnded
    // Error parsing type: , name: allowUserInteraction
}

- (id)init;

@end

