//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

#import "_TtP6TCMask18TCMaskViewDelegate_-Protocol.h"

@class NSLayoutConstraint, UIButton, UICollectionView, UIImageView, UILabel, UIStackView, UIView, _TtC8Stickers13SelectionView, _TtC8Stickers14UICustomButton, _TtC8Stickers19UIAspectImageButton, _TtC8Stickers26ScrollableSegmentedControl;

@interface _TtC8Stickers25PhotoEditorViewController : _TtC8Stickers19BasicViewController <_TtP6TCMask18TCMaskViewDelegate_>
{
    // Error parsing type: , name: canvasView
    // Error parsing type: , name: canvasViewTopConstraint
    // Error parsing type: , name: canvasViewLeadingLayoutConstraint
    // Error parsing type: , name: canvasViewTrailingLayoutConstraint
    // Error parsing type: , name: innerCanvasView
    // Error parsing type: , name: imageView
    // Error parsing type: , name: imageViewHeightConstraint
    // Error parsing type: , name: canvasImageView
    // Error parsing type: , name: canvasBorderImageView
    // Error parsing type: , name: topToolbar
    // Error parsing type: , name: bottomToolbar
    // Error parsing type: , name: doneButton
    // Error parsing type: , name: deleteView
    // Error parsing type: , name: colorsCollectionView
    // Error parsing type: , name: colorPickerView
    // Error parsing type: , name: fontPickerView
    // Error parsing type: , name: fontsCollectionView
    // Error parsing type: , name: strokeSliderView
    // Error parsing type: , name: segmentedControl
    // Error parsing type: , name: controlsStackView
    // Error parsing type: , name: controlsStackViewBottomSafeAreaConstraint
    // Error parsing type: , name: controlsStackViewBottomSuperviewConstraint
    // Error parsing type: , name: undoButton
    // Error parsing type: , name: redoButton
    // Error parsing type: , name: cropButton
    // Error parsing type: , name: stickerButton
    // Error parsing type: , name: drawButton
    // Error parsing type: , name: textButton
    // Error parsing type: , name: borderButton
    // Error parsing type: , name: saveButton
    // Error parsing type: , name: shareButton
    // Error parsing type: , name: clearButton
    // Error parsing type: , name: continueButton
    // Error parsing type: , name: backButton
    // Error parsing type: , name: cancelButton
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: imageButton
    // Error parsing type: , name: toolsButton
    // Error parsing type: , name: extrasButton
    // Error parsing type: , name: borderButton2
    // Error parsing type: , name: selectionView
    // Error parsing type: , name: topWhiteAlphaView
    // Error parsing type: , name: leftWhiteAlphaView
    // Error parsing type: , name: rightWhiteAlphaView
    // Error parsing type: , name: bottomWhiteAlphaView
    // Error parsing type: , name: canvasBackgroundView
    // Error parsing type: , name: toolsContainerView
    // Error parsing type: , name: pageViewControllers
    // Error parsing type: , name: cropButtonImage
    // Error parsing type: , name: stickerButtonImage
    // Error parsing type: , name: drawButtonImage
    // Error parsing type: , name: textButtonImage
    // Error parsing type: , name: saveButtonImage
    // Error parsing type: , name: shareButtonImage
    // Error parsing type: , name: clearButtonImage
    // Error parsing type: , name: continueButtonImage
    // Error parsing type: , name: cancelButtonImage
    // Error parsing type: , name: backupTextViewFont
    // Error parsing type: , name: backupTextViewText
    // Error parsing type: , name: backupTextViewColor
    // Error parsing type: , name: image
    // Error parsing type: , name: eraserView
    // Error parsing type: , name: dismissOnBackButton
    // Error parsing type: , name: packs
    // Error parsing type: , name: colors
    // Error parsing type: , name: photoEditorDelegate
    // Error parsing type: , name: colorsCollectionViewDelegate
    // Error parsing type: , name: fontsCollectionViewDelegate
    // Error parsing type: , name: hiddenControls
    // Error parsing type: , name: stickersVCIsVisible
    // Error parsing type: , name: drawColor
    // Error parsing type: , name: lastPoint
    // Error parsing type: , name: swiped
    // Error parsing type: , name: lastPanPoint
    // Error parsing type: , name: lastTextViewTransform
    // Error parsing type: , name: lastTextViewTransCenter
    // Error parsing type: , name: lastTextViewFont
    // Error parsing type: , name: activeTextView
    // Error parsing type: , name: imageViewToPan
    // Error parsing type: , name: action
    // Error parsing type: , name: drawStrokeSize
    // Error parsing type: , name: borderStrokeSize
    // Error parsing type: , name: radioButtonsController
    // Error parsing type: , name: selectedEditorImageView
    // Error parsing type: , name: photoEditorFonts
    // Error parsing type: , name: stickersViewController
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)photoEditorSelectedEditorImageView:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadView;
@property(nonatomic) __weak UIView *toolsContainerView; // @synthesize toolsContainerView;
@property(nonatomic) __weak UIView *canvasBackgroundView; // @synthesize canvasBackgroundView;
@property(nonatomic) __weak UIView *bottomWhiteAlphaView; // @synthesize bottomWhiteAlphaView;
@property(nonatomic) __weak UIView *rightWhiteAlphaView; // @synthesize rightWhiteAlphaView;
@property(nonatomic) __weak UIView *leftWhiteAlphaView; // @synthesize leftWhiteAlphaView;
@property(nonatomic) __weak UIView *topWhiteAlphaView; // @synthesize topWhiteAlphaView;
@property(nonatomic) __weak _TtC8Stickers13SelectionView *selectionView; // @synthesize selectionView;
@property(nonatomic) __weak UIButton *borderButton2; // @synthesize borderButton2;
@property(nonatomic) __weak UIButton *extrasButton; // @synthesize extrasButton;
@property(nonatomic) __weak UIButton *toolsButton; // @synthesize toolsButton;
@property(nonatomic) __weak UIButton *imageButton; // @synthesize imageButton;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *cancelButton; // @synthesize cancelButton;
@property(nonatomic) __weak _TtC8Stickers19UIAspectImageButton *backButton; // @synthesize backButton;
@property(nonatomic) __weak UIButton *continueButton; // @synthesize continueButton;
@property(nonatomic) __weak UIButton *clearButton; // @synthesize clearButton;
@property(nonatomic) __weak UIButton *shareButton; // @synthesize shareButton;
@property(nonatomic) __weak UIButton *saveButton; // @synthesize saveButton;
@property(nonatomic) __weak UIButton *borderButton; // @synthesize borderButton;
@property(nonatomic) __weak UIButton *textButton; // @synthesize textButton;
@property(nonatomic) __weak UIButton *drawButton; // @synthesize drawButton;
@property(nonatomic) __weak UIButton *stickerButton; // @synthesize stickerButton;
@property(nonatomic) __weak UIButton *cropButton; // @synthesize cropButton;
@property(nonatomic) __weak UIButton *redoButton; // @synthesize redoButton;
@property(nonatomic) __weak UIButton *undoButton; // @synthesize undoButton;
@property(nonatomic) __weak NSLayoutConstraint *controlsStackViewBottomSuperviewConstraint; // @synthesize controlsStackViewBottomSuperviewConstraint;
@property(nonatomic) __weak NSLayoutConstraint *controlsStackViewBottomSafeAreaConstraint; // @synthesize controlsStackViewBottomSafeAreaConstraint;
@property(nonatomic) __weak UIStackView *controlsStackView; // @synthesize controlsStackView;
@property(nonatomic) __weak _TtC8Stickers26ScrollableSegmentedControl *segmentedControl; // @synthesize segmentedControl;
@property(nonatomic) __weak UIView *strokeSliderView; // @synthesize strokeSliderView;
@property(nonatomic) __weak UICollectionView *fontsCollectionView; // @synthesize fontsCollectionView;
@property(nonatomic) __weak UIView *fontPickerView; // @synthesize fontPickerView;
@property(nonatomic) __weak UIView *colorPickerView; // @synthesize colorPickerView;
@property(nonatomic) __weak UICollectionView *colorsCollectionView; // @synthesize colorsCollectionView;
@property(nonatomic) __weak UIView *deleteView; // @synthesize deleteView;
@property(nonatomic) __weak UIButton *doneButton; // @synthesize doneButton;
@property(nonatomic) __weak UIView *bottomToolbar; // @synthesize bottomToolbar;
@property(nonatomic) __weak UIView *topToolbar; // @synthesize topToolbar;
@property(nonatomic) __weak UIImageView *canvasBorderImageView; // @synthesize canvasBorderImageView;
@property(nonatomic) __weak UIImageView *canvasImageView; // @synthesize canvasImageView;
@property(nonatomic) __weak NSLayoutConstraint *imageViewHeightConstraint; // @synthesize imageViewHeightConstraint;
@property(nonatomic, retain) UIImageView *imageView; // @synthesize imageView;
@property(nonatomic) __weak UIView *innerCanvasView; // @synthesize innerCanvasView;
@property(nonatomic) __weak NSLayoutConstraint *canvasViewTrailingLayoutConstraint; // @synthesize canvasViewTrailingLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *canvasViewLeadingLayoutConstraint; // @synthesize canvasViewLeadingLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *canvasViewTopConstraint; // @synthesize canvasViewTopConstraint;
@property(nonatomic) __weak UIView *canvasView; // @synthesize canvasView;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)image:(id)arg1 withPotentialError:(id *)arg2 contextInfo:(void *)arg3;
- (void)continueButtonPressed:(id)arg1;
- (void)clearButtonTapped:(id)arg1;
- (void)shareButtonTapped:(id)arg1;
- (void)saveButtonTapped:(id)arg1;
- (void)doneButtonTapped:(id)arg1;
- (void)cancelButtonTapped:(id)arg1;
- (void)textButtonTapped:(id)arg1;
- (void)borderButtonTapped:(id)arg1;
- (void)drawButtonTapped:(id)arg1;
- (void)stickersButtonTapped:(id)arg1;
- (void)cropButtonTapped:(id)arg1;
- (void)backButtonTapped:(id)arg1;
- (void)redoButtonTapped:(id)arg1;
- (void)undoButtonTapped:(id)arg1;
- (void)tcMaskViewDidExitWithMask:(id)arg1 image:(id)arg2;
- (void)tcMaskViewDidCompleteWithMask:(id)arg1 image:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;
- (void)screenEdgeSwiped:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)tapGesture:(id)arg1;
- (void)rotationGesture:(id)arg1;
- (void)pinchGesture:(id)arg1;
- (void)panGesture:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)changeCursorPositionWithTextView:(id)arg1;

@end

