//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UICollectionView;

@interface _TtC8Stickers24CategoriesViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: categoriesCollectionView
    // Error parsing type: , name: pagesController
    // Error parsing type: , name: sideMenu
    // Error parsing type: , name: sideMenuOrder
    // Error parsing type: , name: lastHeaderContentOffset
    // Error parsing type: , name: lastScrollDirection
    // Error parsing type: , name: group
    // Error parsing type: , name: groups
    // Error parsing type: , name: defaultStickerPacks
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onFilterButton:(id)arg1;
- (void)onBackButton:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)viewDidLoad;
@property(nonatomic) __weak UICollectionView *categoriesCollectionView; // @synthesize categoriesCollectionView;

@end

