//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UICollectionView, UILabel;

@interface _TtC8Stickers29AllStickerPacksViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: helper
    // Error parsing type: , name: identifier
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: minimumInteritemSpacing
    // Error parsing type: , name: minimumLineSpacingPacks
    // Error parsing type: , name: packsPerRow
    // Error parsing type: , name: sideMenu
    // Error parsing type: , name: categories
    // Error parsing type: , name: sideMenuOrder
    // Error parsing type: , name: titleText
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)handleSwipe;
- (void)onFilterButton:(id)arg1;
- (void)onBackButton:(id)arg1;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;
- (void)viewDidLoad;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

