//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface _TtC8Stickers18LoadingViewOverlay : UIView
{
    // Error parsing type: , name: contentView
    // Error parsing type: , name: imageView
    // Error parsing type: , name: activityContainerView
    // Error parsing type: , name: actualAngle
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak UIView *activityContainerView; // @synthesize activityContainerView;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView;
@property(nonatomic, retain) UIView *contentView; // @synthesize contentView;

@end

