//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class NSLayoutConstraint, UILabel, UIScrollView, UIStackView, UITextView, UIView, _TtC8Stickers14UICustomButton;

@interface _TtC8Stickers28TabBarPurchaseViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: startFreeTrialView
    // Error parsing type: , name: startFreeTrialTopLayoutConstraint
    // Error parsing type: , name: priceLabel
    // Error parsing type: , name: joinNowView
    // Error parsing type: , name: noAdsView
    // Error parsing type: , name: subscriptionsStackView
    // Error parsing type: , name: yellowStickersLabel
    // Error parsing type: , name: yellowNewLabel
    // Error parsing type: , name: yellowFavoritesLabel
    // Error parsing type: , name: yellowUnlimitedStickersLabel
    // Error parsing type: , name: yellowUnlimitedEditingLabel
    // Error parsing type: , name: yellowNoAdsLabel
    // Error parsing type: , name: yellowInfoTextView
    // Error parsing type: , name: orangeTitleLabel
    // Error parsing type: , name: orangeItem1TitleLabel
    // Error parsing type: , name: orangeItem2TitleLabel
    // Error parsing type: , name: orangeItem3TitleLabel
    // Error parsing type: , name: orangeItem4TitleLabel
    // Error parsing type: , name: greenTitleLabel
    // Error parsing type: , name: greenSubtitleLabel
    // Error parsing type: , name: greenItem1TitleLabel
    // Error parsing type: , name: greenItem2TitleLabel
    // Error parsing type: , name: greenItem3TitleLabel
    // Error parsing type: , name: greenItem4TitleLabel
    // Error parsing type: , name: redTitleLabel
    // Error parsing type: , name: redSubtitleLabel
    // Error parsing type: , name: secondYellowTitleLabel
    // Error parsing type: , name: secondYellowSubtitleLabel
    // Error parsing type: , name: secondYellowBestValueLabel
    // Error parsing type: , name: secondYellowYearLabel
    // Error parsing type: , name: secondYellowMonthLabel
    // Error parsing type: , name: secondYellowWeekLabel
    // Error parsing type: , name: secondYellowYearlyButton
    // Error parsing type: , name: secondYellowYearlyPriceLabel
    // Error parsing type: , name: secondYellowYearlyAverageLabel
    // Error parsing type: , name: secondYellowYearlySaveLabel
    // Error parsing type: , name: secondYellowMonthlyPriceLabel
    // Error parsing type: , name: secondYellowMonthlyAverageLabel
    // Error parsing type: , name: secondYellowWeeklyPriceLabel
    // Error parsing type: , name: secondYellowWeeklyAverageLabel
    // Error parsing type: , name: secondYellowInfoTextView
    // Error parsing type: , name: privacyPolicyLink
    // Error parsing type: , name: termsOfUseLink
    // Error parsing type: , name: restoreLink
    // Error parsing type: , name: initialStartFreeTrialViewPosition
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onWeeklyButton:(id)arg1;
- (void)onMonthlyButton:(id)arg1;
- (void)onYearlyButton:(id)arg1;
- (void)onStartButton:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UITextView *secondYellowInfoTextView; // @synthesize secondYellowInfoTextView;
@property(nonatomic) __weak UILabel *secondYellowWeeklyAverageLabel; // @synthesize secondYellowWeeklyAverageLabel;
@property(nonatomic) __weak UILabel *secondYellowWeeklyPriceLabel; // @synthesize secondYellowWeeklyPriceLabel;
@property(nonatomic) __weak UILabel *secondYellowMonthlyAverageLabel; // @synthesize secondYellowMonthlyAverageLabel;
@property(nonatomic) __weak UILabel *secondYellowMonthlyPriceLabel; // @synthesize secondYellowMonthlyPriceLabel;
@property(nonatomic) __weak UILabel *secondYellowYearlySaveLabel; // @synthesize secondYellowYearlySaveLabel;
@property(nonatomic) __weak UILabel *secondYellowYearlyAverageLabel; // @synthesize secondYellowYearlyAverageLabel;
@property(nonatomic) __weak UILabel *secondYellowYearlyPriceLabel; // @synthesize secondYellowYearlyPriceLabel;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *secondYellowYearlyButton; // @synthesize secondYellowYearlyButton;
@property(nonatomic) __weak UILabel *secondYellowWeekLabel; // @synthesize secondYellowWeekLabel;
@property(nonatomic) __weak UILabel *secondYellowMonthLabel; // @synthesize secondYellowMonthLabel;
@property(nonatomic) __weak UILabel *secondYellowYearLabel; // @synthesize secondYellowYearLabel;
@property(nonatomic) __weak UILabel *secondYellowBestValueLabel; // @synthesize secondYellowBestValueLabel;
@property(nonatomic) __weak UILabel *secondYellowSubtitleLabel; // @synthesize secondYellowSubtitleLabel;
@property(nonatomic) __weak UILabel *secondYellowTitleLabel; // @synthesize secondYellowTitleLabel;
@property(nonatomic) __weak UILabel *redSubtitleLabel; // @synthesize redSubtitleLabel;
@property(nonatomic) __weak UILabel *redTitleLabel; // @synthesize redTitleLabel;
@property(nonatomic) __weak UILabel *greenItem4TitleLabel; // @synthesize greenItem4TitleLabel;
@property(nonatomic) __weak UILabel *greenItem3TitleLabel; // @synthesize greenItem3TitleLabel;
@property(nonatomic) __weak UILabel *greenItem2TitleLabel; // @synthesize greenItem2TitleLabel;
@property(nonatomic) __weak UILabel *greenItem1TitleLabel; // @synthesize greenItem1TitleLabel;
@property(nonatomic) __weak UILabel *greenSubtitleLabel; // @synthesize greenSubtitleLabel;
@property(nonatomic) __weak UILabel *greenTitleLabel; // @synthesize greenTitleLabel;
@property(nonatomic) __weak UILabel *orangeItem4TitleLabel; // @synthesize orangeItem4TitleLabel;
@property(nonatomic) __weak UILabel *orangeItem3TitleLabel; // @synthesize orangeItem3TitleLabel;
@property(nonatomic) __weak UILabel *orangeItem2TitleLabel; // @synthesize orangeItem2TitleLabel;
@property(nonatomic) __weak UILabel *orangeItem1TitleLabel; // @synthesize orangeItem1TitleLabel;
@property(nonatomic) __weak UILabel *orangeTitleLabel; // @synthesize orangeTitleLabel;
@property(nonatomic) __weak UITextView *yellowInfoTextView; // @synthesize yellowInfoTextView;
@property(nonatomic) __weak UILabel *yellowNoAdsLabel; // @synthesize yellowNoAdsLabel;
@property(nonatomic) __weak UILabel *yellowUnlimitedEditingLabel; // @synthesize yellowUnlimitedEditingLabel;
@property(nonatomic) __weak UILabel *yellowUnlimitedStickersLabel; // @synthesize yellowUnlimitedStickersLabel;
@property(nonatomic) __weak UILabel *yellowFavoritesLabel; // @synthesize yellowFavoritesLabel;
@property(nonatomic) __weak UILabel *yellowNewLabel; // @synthesize yellowNewLabel;
@property(nonatomic) __weak UILabel *yellowStickersLabel; // @synthesize yellowStickersLabel;
@property(nonatomic) __weak UIStackView *subscriptionsStackView; // @synthesize subscriptionsStackView;
@property(nonatomic) __weak UIView *noAdsView; // @synthesize noAdsView;
@property(nonatomic) __weak UIView *joinNowView; // @synthesize joinNowView;
@property(nonatomic) __weak UILabel *priceLabel; // @synthesize priceLabel;
@property(nonatomic) __weak NSLayoutConstraint *startFreeTrialTopLayoutConstraint; // @synthesize startFreeTrialTopLayoutConstraint;
@property(nonatomic) __weak UIView *startFreeTrialView; // @synthesize startFreeTrialView;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView;

@end

