//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UIButton, UILabel, UIStackView, UIView, _TtC8Stickers14DownloadButton, _TtC8Stickers19SmallCategoriesView;

@interface _TtC8Stickers22CategoryViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: databaseManager
    // Error parsing type: , name: categories
    // Error parsing type: , name: hasInfiniteScroll
    // Error parsing type: , name: topNavigationView
    // Error parsing type: , name: stickerCategoryName
    // Error parsing type: , name: downloadButton
    // Error parsing type: , name: downloadAllButton
    // Error parsing type: , name: homeButton
    // Error parsing type: , name: packReleaseDateLabel
    // Error parsing type: , name: menuView
    // Error parsing type: , name: downloadLabel
    // Error parsing type: , name: downloadStackView
    // Error parsing type: , name: dateStackView
    // Error parsing type: , name: packDataView
    // Error parsing type: , name: packUserNameButton
    // Error parsing type: , name: heartLabel
    // Error parsing type: , name: currentStickerPack
    // Error parsing type: , name: pagesController
    // Error parsing type: , name: localCategory
    // Error parsing type: , name: layingOutSubviewsBecauseOfUserAction
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onDownloadButton:(id)arg1;
- (void)onUserNameButton:(id)arg1;
- (void)onDownloadAllButton:(id)arg1;
- (void)onHomeButtonClicked:(id)arg1;
- (void)onRefreshDownloads:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)dealloc;
- (void)viewDidLoad;
- (void)onApplicationDidBecomeActiveWithNotification:(id)arg1;
- (void)onContentWasPutInMemoryWithNotification:(id)arg1;
@property(nonatomic) __weak UIButton *packUserNameButton; // @synthesize packUserNameButton;
@property(nonatomic) __weak UIView *packDataView; // @synthesize packDataView;
@property(nonatomic) __weak UIStackView *dateStackView; // @synthesize dateStackView;
@property(nonatomic) __weak UIStackView *downloadStackView; // @synthesize downloadStackView;
@property(nonatomic) __weak UILabel *downloadLabel; // @synthesize downloadLabel;
@property(nonatomic) __weak _TtC8Stickers19SmallCategoriesView *menuView; // @synthesize menuView;
@property(nonatomic) __weak UILabel *packReleaseDateLabel; // @synthesize packReleaseDateLabel;
@property(nonatomic) __weak UIButton *homeButton; // @synthesize homeButton;
@property(nonatomic) __weak UIButton *downloadAllButton; // @synthesize downloadAllButton;
@property(nonatomic) __weak _TtC8Stickers14DownloadButton *downloadButton; // @synthesize downloadButton;
@property(nonatomic) __weak UILabel *stickerCategoryName; // @synthesize stickerCategoryName;
@property(nonatomic) __weak UIView *topNavigationView; // @synthesize topNavigationView;

@end

