//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel, UIView;

@interface _TtC8Stickers29BigCategoryCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: selectedView
    // Error parsing type: , name: stickerCategoryImageView
    // Error parsing type: , name: categoryLabel
    // Error parsing type: , name: group
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)prepareForReuse;
- (void)OnSelectBigCategory:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
@property(nonatomic) __weak UILabel *categoryLabel; // @synthesize categoryLabel;
@property(nonatomic) __weak UIImageView *stickerCategoryImageView; // @synthesize stickerCategoryImageView;
@property(nonatomic) __weak UIView *selectedView; // @synthesize selectedView;

@end

