//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Stickers14RemoteCategory : _TtCs12_SwiftObject
{
    // Error parsing type: , name: id
    // Error parsing type: , name: categoryDescription
    // Error parsing type: , name: categoryID
    // Error parsing type: , name: categoryIconFile
    // Error parsing type: , name: whatsAppIconFile
    // Error parsing type: , name: categoryName
    // Error parsing type: , name: createdAt
    // Error parsing type: , name: updatedAt
    // Error parsing type: , name: releasedAt
    // Error parsing type: , name: priority
    // Error parsing type: , name: numberOfStickers
    // Error parsing type: , name: color
    // Error parsing type: , name: userID
    // Error parsing type: , name: userName
    // Error parsing type: , name: userProfileImage
    // Error parsing type: , name: status
    // Error parsing type: , name: groups
    // Error parsing type: , name: isFree
    // Error parsing type: , name: isOriginal
    // Error parsing type: , name: isCustom
    // Error parsing type: , name: isPhoto
    // Error parsing type: , name: isAnimated
    // Error parsing type: , name: originalsFile
    // Error parsing type: , name: publishedCategoryID
    // Error parsing type: , name: originalCategoryID
    // Error parsing type: , name: accessoryOrder
    // Error parsing type: , name: isDailyPack
}

@end

