//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UICollectionView;

@interface _TtC8Stickers24SaveToPackViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: myPacks
    // Error parsing type: , name: onSelectStickerPack
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onBackButton:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

