//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class NSLayoutConstraint, UICollectionView, UIImageView, UILabel, UIView;

@interface _TtC8Stickers27PublicProfileViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: profileImageView
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: collectionViewHeightLayoutConstraint
    // Error parsing type: , name: nameLabel
    // Error parsing type: , name: contentView
    // Error parsing type: , name: headerView
    // Error parsing type: , name: headerViewTopLayoutConstraint
    // Error parsing type: , name: stickerPacks
    // Error parsing type: , name: previousScrollOffset
    // Error parsing type: , name: minHeaderTop
    // Error parsing type: , name: maxHeaderTop
    // Error parsing type: , name: userID
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onBackButton:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak NSLayoutConstraint *headerViewTopLayoutConstraint; // @synthesize headerViewTopLayoutConstraint;
@property(nonatomic) __weak UIView *headerView; // @synthesize headerView;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel;
@property(nonatomic) __weak NSLayoutConstraint *collectionViewHeightLayoutConstraint; // @synthesize collectionViewHeightLayoutConstraint;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UIImageView *profileImageView; // @synthesize profileImageView;

@end

