//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers14DailyTextField.h"

@interface _TtC8Stickers17UITextPickerField : _TtC8Stickers14DailyTextField
{
    // Error parsing type: , name: pickerView
    // Error parsing type: , name: pickItems
}

- (void).cxx_destruct;
- (void)donePickerView;
- (void)cancelPickerView;
- (struct CGRect)caretRectForPosition:(id)arg1;
- (_Bool)shouldChangeTextInRange:(id)arg1 replacementText:(id)arg2;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

