//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC8Stickers11UsedSticker : NSObject
{
    // Error parsing type: , name: id
    // Error parsing type: , name: stickerID
    // Error parsing type: , name: categoryID
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSString *categoryID; // @synthesize categoryID;
@property(nonatomic, copy) NSString *stickerID; // @synthesize stickerID;
@property(nonatomic, copy) NSString *id; // @synthesize id;

@end

