//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Stickers13RemoteSticker : _TtCs12_SwiftObject
{
    // Error parsing type: , name: id
    // Error parsing type: , name: stickerDescription
    // Error parsing type: , name: categoryID
    // Error parsing type: , name: stickerIconFile
    // Error parsing type: , name: animatedStickerIconFile
    // Error parsing type: , name: whatsAppIconFile
    // Error parsing type: , name: status
    // Error parsing type: , name: order
    // Error parsing type: , name: groups
    // Error parsing type: , name: createdAt
    // Error parsing type: , name: updatedAt
    // Error parsing type: , name: originalCategoryID
    // Error parsing type: , name: originalStickerID
}

@end

