//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$s10RealmSwift6ObjectCN.h"

@class NSString;

@interface _TtC8Stickers21RealmCategoryDownload : _$s10RealmSwift6ObjectCN
{
    // Error parsing type: , name: id
    // Error parsing type: , name: library
    // Error parsing type: , name: message
    // Error parsing type: , name: whatsapp
    // Error parsing type: , name: createdAt
    // Error parsing type: , name: updatedAt
}

+ (id)primaryKey;
- (void).cxx_destruct;
- (id)initWithValue:(id)arg1 schema:(id)arg2;
- (id)initWithRealm:(id)arg1 schema:(id)arg2;
- (id)init;
@property(nonatomic) long long updatedAt; // @synthesize updatedAt;
@property(nonatomic) long long createdAt; // @synthesize createdAt;
@property(nonatomic) long long whatsapp; // @synthesize whatsapp;
@property(nonatomic) long long message; // @synthesize message;
@property(nonatomic) long long library; // @synthesize library;
@property(nonatomic, copy) NSString *id; // @synthesize id;

@end

