//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UICollectionView, UISearchBar, _TtC8Stickers12SelectButton;

@interface _TtC8Stickers24SearchHomeViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: searchBar
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: packsButton
    // Error parsing type: , name: stickersButton
    // Error parsing type: , name: creatorsButton
    // Error parsing type: , name: clearButton
    // Error parsing type: , name: identifier
    // Error parsing type: , name: shuffledGroups
    // Error parsing type: , name: searchData
    // Error parsing type: , name: filteredSearchData
    // Error parsing type: , name: searchDelay
    // Error parsing type: , name: searchTimer
    // Error parsing type: , name: lastSearchText
    // Error parsing type: , name: isAlreadySearching
    // Error parsing type: , name: needFilterAgain
    // Error parsing type: , name: isSearching
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onSearchTimer;
- (void)onClearButton:(id)arg1;
- (void)onCreatorsButton:(id)arg1;
- (void)onStickersButton:(id)arg1;
- (void)onPacksButton:(id)arg1;
- (void)onReloadStickersNotificationWithNotification:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak _TtC8Stickers12SelectButton *clearButton; // @synthesize clearButton;
@property(nonatomic) __weak _TtC8Stickers12SelectButton *creatorsButton; // @synthesize creatorsButton;
@property(nonatomic) __weak _TtC8Stickers12SelectButton *stickersButton; // @synthesize stickersButton;
@property(nonatomic) __weak _TtC8Stickers12SelectButton *packsButton; // @synthesize packsButton;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UISearchBar *searchBar; // @synthesize searchBar;

@end

