//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface _TtC8Stickers11PurchaseLog : NSObject
{
    // Error parsing type: , name: transactionId
    // Error parsing type: , name: productId
    // Error parsing type: , name: purchaseDate
    // Error parsing type: , name: isTrialPeriod
    // Error parsing type: , name: synchronized
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) _Bool synchronized; // @synthesize synchronized;
@property(nonatomic) _Bool isTrialPeriod; // @synthesize isTrialPeriod;
@property(nonatomic, copy) NSDate *purchaseDate; // @synthesize purchaseDate;
@property(nonatomic, copy) NSString *productId; // @synthesize productId;
@property(nonatomic, copy) NSString *transactionId; // @synthesize transactionId;

@end

