//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers10BaseButton.h"

@class NSString, UIColor;

@interface _TtC8Stickers14UICustomButton : _TtC8Stickers10BaseButton
{
    // Error parsing type: , name: cornerRadius
    // Error parsing type: , name: roundedCorner
    // Error parsing type: , name: borderWidth
    // Error parsing type: , name: borderColor
    // Error parsing type: , name: shadowOffset
    // Error parsing type: , name: shadowColor
    // Error parsing type: , name: stringID
}

- (void).cxx_destruct;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)prepareForInterfaceBuilder;
@property(nonatomic, copy) NSString *stringID; // @synthesize stringID;
@property(nonatomic, retain) UIColor *shadowColor; // @synthesize shadowColor;
@property(nonatomic) struct CGSize shadowOffset; // @synthesize shadowOffset;
@property(nonatomic, retain) UIColor *borderColor; // @synthesize borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(nonatomic) _Bool roundedCorner; // @synthesize roundedCorner;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

