//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UITableView, _TtC8Stickers10BaseButton;

@interface _TtC8Stickers17FAQViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: backButton
    // Error parsing type: , name: faqs
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onBackButton:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak _TtC8Stickers10BaseButton *backButton; // @synthesize backButton;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;

@end

