//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UIButton;

@interface _TtC8Stickers22SortMenuViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: alphabeticalCheckOrderButton
    // Error parsing type: , name: trendingCheckOrderButton
    // Error parsing type: , name: newestCheckOrderButton
    // Error parsing type: , name: randomCheckOrderButton
    // Error parsing type: , name: delegate
    // Error parsing type: , name: currentOrder
    // Error parsing type: , name: handleDismiss
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onRandomOrderButton:(id)arg1;
- (void)onNewestOrderButton:(id)arg1;
- (void)onTrendingOrderButton:(id)arg1;
- (void)onAlphabeticalOrderButton:(id)arg1;
- (void)onCloseButton:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UIButton *randomCheckOrderButton; // @synthesize randomCheckOrderButton;
@property(nonatomic) __weak UIButton *newestCheckOrderButton; // @synthesize newestCheckOrderButton;
@property(nonatomic) __weak UIButton *trendingCheckOrderButton; // @synthesize trendingCheckOrderButton;
@property(nonatomic) __weak UIButton *alphabeticalCheckOrderButton; // @synthesize alphabeticalCheckOrderButton;

@end

