//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Stickers15FirebaseManager : _TtCs12_SwiftObject
{
    // Error parsing type: , name: config
    // Error parsing type: , name: db
    // Error parsing type: , name: groupsReference
    // Error parsing type: , name: categoriesReference
    // Error parsing type: , name: allStickersReference
    // Error parsing type: , name: downloadsReference
    // Error parsing type: , name: usersReference
    // Error parsing type: , name: reportsReference
    // Error parsing type: , name: highlightsReference
    // Error parsing type: , name: userPacksReference
    // Error parsing type: , name: userStickersReference
    // Error parsing type: , name: mainReference
    // Error parsing type: , name: regionsReference
}

- (void)configureFirebaseOnComplete:(CDUnknownBlockType)arg1;
- (void)onUserDidAuthenticateWithNotification:(id)arg1;

@end

