//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Stickers11RemoteGroup : _TtCs12_SwiftObject
{
    // Error parsing type: , name: id
    // Error parsing type: , name: coverURL
    // Error parsing type: , name: coverNoTitleURL
    // Error parsing type: , name: headerURL
    // Error parsing type: , name: name
    // Error parsing type: , name: numberOfCategories
    // Error parsing type: , name: numberOfStickers
    // Error parsing type: , name: color
    // Error parsing type: , name: createdAt
    // Error parsing type: , name: updatedAt
    // Error parsing type: , name: status
    // Error parsing type: , name: homeOrder
    // Error parsing type: , name: packCellType
}

@end

