//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPageViewController.h>

@interface _TtC8Stickers27StickersPagesViewController : UIPageViewController
{
    // Error parsing type: , name: contentManager
    // Error parsing type: , name: helper
    // Error parsing type: , name: categories
    // Error parsing type: , name: parentDelegate
    // Error parsing type: , name: pages.storage
    // Error parsing type: , name: currentViewController
    // Error parsing type: , name: currentViewControllerBackup
}

- (void).cxx_destruct;
- (id)initWithTransitionStyle:(long long)arg1 navigationOrientation:(long long)arg2 options:(id)arg3;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

