//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers26BasePurchaseViewController.h"

@class UIButton, UICollectionView, UILabel, UIPageControl, _TtC8Stickers14UICustomButton;

@interface _TtC8Stickers30CarouselPurchaseViewController : _TtC8Stickers26BasePurchaseViewController
{
    // Error parsing type: , name: moreOptionsButton
    // Error parsing type: , name: startButton
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: restoreButton
    // Error parsing type: , name: pageControl
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: scrollTimer
    // Error parsing type: , name: dummyPaywallImagesCount
    // Error parsing type: , name: paywallImages
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)rotate;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak UIPageControl *pageControl; // @synthesize pageControl;
@property(nonatomic) __weak UIButton *restoreButton; // @synthesize restoreButton;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *startButton; // @synthesize startButton;
@property(nonatomic) __weak UIButton *moreOptionsButton; // @synthesize moreOptionsButton;

@end

