//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Stickers11StickerPack : _TtCs12_SwiftObject
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: name
    // Error parsing type: , name: publisher
    // Error parsing type: , name: trayImage
    // Error parsing type: , name: publisherWebsite
    // Error parsing type: , name: privacyPolicyWebsite
    // Error parsing type: , name: licenseAgreementWebsite
    // Error parsing type: , name: stickers
}

@end

