//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@interface _TtC8Stickers12PulsingLayer : CALayer
{
    // Error parsing type: , name: animationGroup
    // Error parsing type: , name: initialPulseScale
    // Error parsing type: , name: nextPulseAfter
    // Error parsing type: , name: animationDuration
    // Error parsing type: , name: radius
    // Error parsing type: , name: numberOfPulses
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithLayer:(id)arg1;

@end

