//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UIActivityIndicatorView, UIImageView;

@interface _TtC8Stickers29PosLaunchScreenViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: backgroundImageView
    // Error parsing type: , name: activityIndicatorView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onIapProductArrivalWithNotification:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView;
@property(nonatomic) __weak UIImageView *backgroundImageView; // @synthesize backgroundImageView;

@end

