//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC8Stickers8CropView : UIView
{
    // Error parsing type: , name: image
    // Error parsing type: , name: imageView
    // Error parsing type: , name: keepAspectRatio
    // Error parsing type: , name: imageCropRect
    // Error parsing type: , name: resizeEnabled
    // Error parsing type: , name: showCroppedArea
    // Error parsing type: , name: rotationGestureRecognizer
    // Error parsing type: , name: imageSize
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: zoomingView
    // Error parsing type: , name: cropRectView
    // Error parsing type: , name: topOverlayView
    // Error parsing type: , name: leftOverlayView
    // Error parsing type: , name: rightOverlayView
    // Error parsing type: , name: bottomOverlayView
    // Error parsing type: , name: insetRect
    // Error parsing type: , name: editingRect
    // Error parsing type: , name: interfaceOrientation
    // Error parsing type: , name: resizing
    // Error parsing type: , name: usingCustomImageView
    // Error parsing type: , name: MarginTop
    // Error parsing type: , name: MarginLeft
}

- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint *)arg3;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)handleRotation:(id)arg1;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

