//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC8Stickers15EditorImageView : UIView
{
    // Error parsing type: , name: imageView
    // Error parsing type: , name: maskImageView
    // Error parsing type: , name: lastPoint
    // Error parsing type: , name: sectionSnapshotCount
    // Error parsing type: , name: delegate
    // Error parsing type: , name: eraserSize
    // Error parsing type: , name: eraserAction
    // Error parsing type: , name: image
    // Error parsing type: , name: isSelected
}

- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

