//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtCC8Stickers26ScrollableSegmentedControlP33_BBFC12BAAA4C960ACF4034D51EEDD4AE34BaseImageSegmentCollectionViewCell.h"

@interface _TtCC8Stickers26ScrollableSegmentedControlP33_BBFC12BAAA4C960ACF4034D51EEDD4AE35ImageOnTopSegmentCollectionViewCell : _TtCC8Stickers26ScrollableSegmentedControlP33_BBFC12BAAA4C960ACF4034D51EEDD4AE34BaseImageSegmentCollectionViewCell
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

