//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8Stickers15GoogleAdManager : NSObject
{
    // Error parsing type: , name: kGoogleInterstitialName
    // Error parsing type: , name: bannerView
    // Error parsing type: , name: interstitial
    // Error parsing type: , name: delegate
    // Error parsing type: , name: isInterstitialReady
    // Error parsing type: , name: isBannerReady
    // Error parsing type: , name: numberOfPresentedInterstitial
    // Error parsing type: , name: onDidReceiveInterstitialAd
    // Error parsing type: , name: onDidDismissInterstitialAd
}

- (void).cxx_destruct;
- (id)init;

@end

