//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers10BaseButton.h"

@class UIColor;

@interface _TtC8Stickers19UIAspectImageButton : _TtC8Stickers10BaseButton
{
    // Error parsing type: , name: imageWidthProportion
    // Error parsing type: , name: imageProportion
    // Error parsing type: , name: cornerRadius
    // Error parsing type: , name: borderWidth
    // Error parsing type: , name: borderColor
}

- (void).cxx_destruct;
@property(nonatomic, retain) UIColor *borderColor; // @synthesize borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius;
@property(nonatomic) double imageProportion; // @synthesize imageProportion;
- (void)layoutSubviews;
@property(nonatomic) double imageWidthProportion; // @synthesize imageWidthProportion;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

