//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UIImageView, UIView, _TtC8Stickers14DownloadButton, _TtC8Stickers19PopupBackgroundView;

@interface _TtC8Stickers28StickerPreviewViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: containerView
    // Error parsing type: , name: stickerImageView
    // Error parsing type: , name: popupBackgroundView
    // Error parsing type: , name: downloadButton
    // Error parsing type: , name: stickerImage
    // Error parsing type: , name: sticker
    // Error parsing type: , name: stickerPack
    // Error parsing type: , name: onStartDownloading
    // Error parsing type: , name: onCallSaveStickersTo
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onDownloadButton:(id)arg1;
- (void)onDownloadAllButton:(id)arg1;
- (void)onCloseButton:(id)arg1;
- (void)onContainerViewTap:(id)arg1;
- (void)onBackgroundViewTap:(id)arg1;
- (void)onFavoritedStickerNotification:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
@property(nonatomic) __weak _TtC8Stickers14DownloadButton *downloadButton; // @synthesize downloadButton;
@property(nonatomic) __weak _TtC8Stickers19PopupBackgroundView *popupBackgroundView; // @synthesize popupBackgroundView;
@property(nonatomic) __weak UIImageView *stickerImageView; // @synthesize stickerImageView;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView;

@end

