//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8Stickers6Config : NSObject
{
    // Error parsing type: , name: userIsAuthenticated
    // Error parsing type: , name: configsRemoteSourceSetupHasBeenRequested
    // Error parsing type: , name: configsRemoteSourceIsSetup
    // Error parsing type: , name: contentRemoteSourceIsSetup
    // Error parsing type: , name: configsHaveArrivedFromRemote
    // Error parsing type: , name: contentHasArrivedFromRemote
    // Error parsing type: , name: contentHasBeenLoadedToMemory
    // Error parsing type: , name: isSynchronizingStickers
    // Error parsing type: , name: firebaseId
    // Error parsing type: , name: products
    // Error parsing type: , name: iapProductsHaveBeenRequested
    // Error parsing type: , name: iapProductsHaveArrived
    // Error parsing type: , name: remoteConfigsHaveArrived
    // Error parsing type: , name: iadAdGroupId
    // Error parsing type: , name: paywallDisabled
    // Error parsing type: , name: freePacksEnabled
    // Error parsing type: , name: numberOfPacksPerCarousel
    // Error parsing type: , name: numberOfHomeCategories
    // Error parsing type: , name: minimalVersion
    // Error parsing type: , name: freeTrialDownloadLimit
    // Error parsing type: , name: paywallDisabledByAds
    // Error parsing type: , name: developerMode
    // Error parsing type: , name: adTrackingIsEnabled
    // Error parsing type: , name: isFirstOpening
    // Error parsing type: , name: releaseVersion
    // Error parsing type: , name: paywallTypeWithoutCheckingVersion
    // Error parsing type: , name: paywallType
    // Error parsing type: , name: appleCampaignsWithoutCheckingVersion
    // Error parsing type: , name: appleCampaigns
    // Error parsing type: , name: xButtonAppearance
    // Error parsing type: , name: purchaseLoggingMethod
    // Error parsing type: , name: dollarsPerPurchase
    // Error parsing type: , name: mainProduct
    // Error parsing type: , name: longFrequencyProduct
    // Error parsing type: , name: mediumFrequencyProduct
    // Error parsing type: , name: shortFrequencyProduct
    // Error parsing type: , name: defaultProduct
    // Error parsing type: , name: defaultLongFrequencyProduct
    // Error parsing type: , name: defaultMediumFrequencyProduct
    // Error parsing type: , name: defaultShortFrequencyProduct
    // Error parsing type: , name: defaultIapShortIdFromRemoteConfig
    // Error parsing type: , name: lastViewControllerClass
    // Error parsing type: , name: lastViewControllerName
    // Error parsing type: , name: adFreeUsers
    // Error parsing type: , name: useRemotePurchaseVerification
    // Error parsing type: , name: askForAppRate
    // Error parsing type: , name: fastReview
    // Error parsing type: , name: showThankYouView
    // Error parsing type: , name: homeFinishedTimestamp
    // Error parsing type: , name: lastPresentedInterstitialTimestamp
    // Error parsing type: , name: enableInterstitialsAfter
    // Error parsing type: , name: nextInterstitialAfter
}

- (void).cxx_destruct;
- (id)init;

@end

