//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers25PhotoEditorViewController.h"

#import "_TtP8Stickers21BasicKeyboardDelegate_-Protocol.h"

@interface _TtC8Stickers25PhotoEditorViewController (Stickers3) <_TtP8Stickers21BasicKeyboardDelegate_>
- (void)basicKeyboardDidHideWithResult:(id)arg1;
- (void)basicKeyboardDidShowWithResult:(id)arg1;
@end

