//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class _TtC8Stickers17UISubtitledButton;

@interface _TtC8Stickers25EditorImageViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: libraryButton
    // Error parsing type: , name: cameraButton
    // Error parsing type: , name: stickersButton
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onStickersButton:(id)arg1;
- (void)onCameraButton:(id)arg1;
- (void)onLibraryButton:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak _TtC8Stickers17UISubtitledButton *stickersButton; // @synthesize stickersButton;
@property(nonatomic) __weak _TtC8Stickers17UISubtitledButton *cameraButton; // @synthesize cameraButton;
@property(nonatomic) __weak _TtC8Stickers17UISubtitledButton *libraryButton; // @synthesize libraryButton;

@end

