//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class UIPageControl, UIScrollView, UIView;

@interface _TtC8Stickers33PhotoEditorStickersViewController : _TtC8Stickers19BasicViewController <UIGestureRecognizerDelegate>
{
    // Error parsing type: , name: headerView
    // Error parsing type: , name: holdView
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: pageControl
    // Error parsing type: , name: lastY
    // Error parsing type: , name: lastOffset
    // Error parsing type: , name: stickersTask
    // Error parsing type: , name: emojisCollectioView
    // Error parsing type: , name: emojisDelegate
    // Error parsing type: , name: carouselScrollView
    // Error parsing type: , name: packs
    // Error parsing type: , name: stickersViewControllerDelegate
    // Error parsing type: , name: screenSize
    // Error parsing type: , name: fullView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onAddPacksWithNotification:(id)arg1;
- (void)panGesture:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
@property(nonatomic) __weak UIPageControl *pageControl; // @synthesize pageControl;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView;
@property(nonatomic) __weak UIView *holdView; // @synthesize holdView;
@property(nonatomic) __weak UIView *headerView; // @synthesize headerView;

@end

