//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@interface _TtC8Stickers24BasicPopUpViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: centerYConstrant
    // Error parsing type: , name: viewScale
    // Error parsing type: , name: viewAlpha
    // Error parsing type: , name: onViewWillDisappear
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)customKeyboardWillHideNotification:(id)arg1;
- (void)customKeyboardWillShowNotification:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

