//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC8Stickers13LocalCategory : NSObject
{
    // Error parsing type: , name: id
    // Error parsing type: , name: categoryDescription
    // Error parsing type: , name: categoryID
    // Error parsing type: , name: categoryIconFile
    // Error parsing type: , name: whatsAppIconFile
    // Error parsing type: , name: categoryName
    // Error parsing type: , name: createdAt
    // Error parsing type: , name: updatedAt
    // Error parsing type: , name: releasedAt
    // Error parsing type: , name: priority
    // Error parsing type: , name: messageDownloadStatus
    // Error parsing type: , name: libraryDownloadStatus
    // Error parsing type: , name: whatsappDownloadStatus
    // Error parsing type: , name: numberOfStickers
    // Error parsing type: , name: color
    // Error parsing type: , name: totalDownloads
    // Error parsing type: , name: orderPriority
    // Error parsing type: , name: displays
    // Error parsing type: , name: openings
    // Error parsing type: , name: userID
    // Error parsing type: , name: userName
    // Error parsing type: , name: userProfileImage
    // Error parsing type: , name: status
    // Error parsing type: , name: isFree
    // Error parsing type: , name: isOriginal
    // Error parsing type: , name: isCustom
    // Error parsing type: , name: isPhoto
    // Error parsing type: , name: isAnimated
    // Error parsing type: , name: originalsFile
    // Error parsing type: , name: publishedCategoryID
    // Error parsing type: , name: originalCategoryID
    // Error parsing type: , name: accessoryOrder
    // Error parsing type: , name: ownedAt
    // Error parsing type: , name: isDailyPack
    // Error parsing type: , name: editorLocalFilename
    // Error parsing type: , name: lastUpdate
    // Error parsing type: , name: lastUpload
    // Error parsing type: , name: needUploadImages
    // Error parsing type: , name: needUpload
    // Error parsing type: , name: groups
    // Error parsing type: , name: stickers
}

- (void).cxx_destruct;
@property(nonatomic) _Bool needUpload; // @synthesize needUpload;
@property(nonatomic) _Bool needUploadImages; // @synthesize needUploadImages;
@property(nonatomic) long long lastUpload; // @synthesize lastUpload;
@property(nonatomic) long long lastUpdate; // @synthesize lastUpdate;
@property(nonatomic, copy) NSString *editorLocalFilename; // @synthesize editorLocalFilename;
@property(nonatomic) _Bool isDailyPack; // @synthesize isDailyPack;
@property(nonatomic) long long ownedAt; // @synthesize ownedAt;
@property(nonatomic) long long accessoryOrder; // @synthesize accessoryOrder;
@property(nonatomic, copy) NSString *originalCategoryID; // @synthesize originalCategoryID;
@property(nonatomic, copy) NSString *publishedCategoryID; // @synthesize publishedCategoryID;
@property(nonatomic, copy) NSString *originalsFile; // @synthesize originalsFile;
@property(nonatomic) _Bool isAnimated; // @synthesize isAnimated;
@property(nonatomic) _Bool isPhoto; // @synthesize isPhoto;
@property(nonatomic) _Bool isCustom; // @synthesize isCustom;
@property(nonatomic) _Bool isOriginal; // @synthesize isOriginal;
@property(nonatomic) _Bool isFree; // @synthesize isFree;
@property(nonatomic) long long status; // @synthesize status;
@property(nonatomic, copy) NSString *userProfileImage; // @synthesize userProfileImage;
@property(nonatomic, copy) NSString *userName; // @synthesize userName;
@property(nonatomic, copy) NSString *userID; // @synthesize userID;
@property(nonatomic) long long openings; // @synthesize openings;
@property(nonatomic) long long displays; // @synthesize displays;
@property(nonatomic) long long orderPriority; // @synthesize orderPriority;
@property(nonatomic) long long totalDownloads; // @synthesize totalDownloads;
@property(nonatomic, copy) NSString *color; // @synthesize color;
@property(nonatomic) long long numberOfStickers; // @synthesize numberOfStickers;
@property(nonatomic) long long whatsappDownloadStatus; // @synthesize whatsappDownloadStatus;
@property(nonatomic) long long libraryDownloadStatus; // @synthesize libraryDownloadStatus;
@property(nonatomic) long long messageDownloadStatus; // @synthesize messageDownloadStatus;
@property(nonatomic) long long priority; // @synthesize priority;
@property(nonatomic) long long releasedAt; // @synthesize releasedAt;
@property(nonatomic) long long updatedAt; // @synthesize updatedAt;
@property(nonatomic) long long createdAt; // @synthesize createdAt;
@property(nonatomic, copy) NSString *categoryName; // @synthesize categoryName;
@property(nonatomic, copy) NSString *whatsAppIconFile; // @synthesize whatsAppIconFile;
@property(nonatomic, copy) NSString *categoryIconFile; // @synthesize categoryIconFile;
@property(nonatomic, copy) NSString *categoryID; // @synthesize categoryID;
@property(nonatomic, copy) NSString *categoryDescription; // @synthesize categoryDescription;
@property(nonatomic, copy) NSString *id; // @synthesize id;
- (void)onUpdateUserData:(id)arg1;
- (void)dealloc;
- (id)init;

@end

