//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView, _TtC8Stickers14UICustomButton, _TtC8Stickers18PackCollectionView;

@interface _TtC8Stickers39LabeledStickerPackCarouselTableViewCell : UITableViewCell
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: emptyCollectionLabel
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: leftContainerView
    // Error parsing type: , name: seeAllButton
    // Error parsing type: , name: freeStickerPacks
    // Error parsing type: , name: trimmedFreeStickerPacks
    // Error parsing type: , name: stickerPacks
    // Error parsing type: , name: emptyMessage
    // Error parsing type: , name: category
    // Error parsing type: , name: cellType
    // Error parsing type: , name: seeAllButtonTimer
    // Error parsing type: , name: isAnimatingSeeAllButton
    // Error parsing type: , name: dailyPacksAvailable
    // Error parsing type: , name: showSeeAllCell
    // Error parsing type: , name: isDailyPacks
    // Error parsing type: , name: delegate
    // Error parsing type: , name: dailyPacksDelegate
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)onSeeAllButtonTimer;
- (void)onSeeAllButton:(id)arg1;
- (void)onTitleTapGesture;
- (void)onUnlockedStickerPack:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)prepareForReuse;
- (void)awakeFromNib;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *seeAllButton; // @synthesize seeAllButton;
@property(nonatomic) __weak UIView *leftContainerView; // @synthesize leftContainerView;
@property(nonatomic) __weak _TtC8Stickers18PackCollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UILabel *emptyCollectionLabel; // @synthesize emptyCollectionLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;

@end

