//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, UITextField, UITextView, _TtC8Stickers14UICustomButton;

@interface _TtC8Stickers17CustomImproveView : UIView
{
    // Error parsing type: , name: contentView
    // Error parsing type: , name: messageTextView
    // Error parsing type: , name: emailTextField
    // Error parsing type: , name: sendButton
    // Error parsing type: , name: viewCenterY
    // Error parsing type: , name: onDismiss
    // Error parsing type: , name: onSend
}

- (void).cxx_destruct;
- (void)customKeyboardWillHideNotification:(id)arg1;
- (void)customKeyboardWillShowNotification:(id)arg1;
- (void)onCloseButton:(id)arg1;
- (void)onSendButton:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak NSLayoutConstraint *viewCenterY; // @synthesize viewCenterY;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *sendButton; // @synthesize sendButton;
@property(nonatomic) __weak UITextField *emailTextField; // @synthesize emailTextField;
@property(nonatomic) __weak UITextView *messageTextView; // @synthesize messageTextView;
@property(nonatomic, retain) UIView *contentView; // @synthesize contentView;

@end

