//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Stickers14ContentManager : _TtCs12_SwiftObject
{
    // Error parsing type: , name: backendManager
    // Error parsing type: , name: databaseManager
    // Error parsing type: , name: libraryManager
    // Error parsing type: , name: dataTransferManager
    // Error parsing type: , name: fileManager
    // Error parsing type: , name: imageDownloadManager
    // Error parsing type: , name: purchaseManager
    // Error parsing type: , name: notificationHelper
    // Error parsing type: , name: config
    // Error parsing type: , name: user
    // Error parsing type: , name: groupFilterType
    // Error parsing type: , name: homeCategories
    // Error parsing type: , name: isSynchronizingUserPacks
    // Error parsing type: , name: backgroundTaskID
    // Error parsing type: , name: numberOfChainedUserUploads
    // Error parsing type: , name: cancelCurrentUpload
    // Error parsing type: , name: unsafePacks
    // Error parsing type: , name: unsafePacksByPopularity
    // Error parsing type: , name: unsafeGroups
    // Error parsing type: , name: unsafeUserPacks
    // Error parsing type: , name: unsafeFreePacks
    // Error parsing type: , name: unsafeNewPacks
    // Error parsing type: , name: unsafeCommunityPacks
    // Error parsing type: , name: unsafeOriginalPacks
    // Error parsing type: , name: unsafeAnimatedPacks
    // Error parsing type: , name: unsafeHighlights
    // Error parsing type: , name: packsQueue
    // Error parsing type: , name: groupsQueue
    // Error parsing type: , name: highlightsQueue
    // Error parsing type: , name: accessoryPacks
}

- (void)getAndPersistAllRemoteStickersAndNotifyOnComplete:(CDUnknownBlockType)arg1;
- (void)getAndPersistAllRemoteObjectsAndNotifyOnComplete:(CDUnknownBlockType)arg1;
- (void)onContentRemoteSourceIsSetupWithNotification:(id)arg1;

@end

