//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UISlider.h>

@class UIColor;

@interface _TtC8Stickers10StepSlider : UISlider
{
    // Error parsing type: , name: steps
    // Error parsing type: , name: minValue
    // Error parsing type: , name: maxValue
    // Error parsing type: , name: customTrack
    // Error parsing type: , name: minTrackHeight
    // Error parsing type: , name: maxTrackHeight
    // Error parsing type: , name: minTrackColor
    // Error parsing type: , name: maxTrackColor
    // Error parsing type: , name: stepTickWidth
    // Error parsing type: , name: stepTickHeight
    // Error parsing type: , name: stepTickColor
    // Error parsing type: , name: stepTickRounded
    // Error parsing type: , name: previousLocation
    // Error parsing type: , name: dragging
    // Error parsing type: , name: originalValue
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;
@property(nonatomic) _Bool stepTickRounded; // @synthesize stepTickRounded;
@property(nonatomic, retain) UIColor *stepTickColor; // @synthesize stepTickColor;
@property(nonatomic) double stepTickHeight; // @synthesize stepTickHeight;
@property(nonatomic) long long stepTickWidth; // @synthesize stepTickWidth;
@property(nonatomic, retain) UIColor *maxTrackColor; // @synthesize maxTrackColor;
@property(nonatomic, retain) UIColor *minTrackColor; // @synthesize minTrackColor;
@property(nonatomic) long long maxTrackHeight; // @synthesize maxTrackHeight;
@property(nonatomic) long long minTrackHeight; // @synthesize minTrackHeight;
@property(nonatomic) _Bool customTrack; // @synthesize customTrack;
@property(nonatomic) float maxValue; // @synthesize maxValue;
@property(nonatomic) float minValue; // @synthesize minValue;
@property(nonatomic) long long steps; // @synthesize steps;

@end

