//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers33BaseStickerPackCollectionViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel;

@interface _TtC8Stickers32NewStickerPackCollectionViewCell : _TtC8Stickers33BaseStickerPackCollectionViewCell
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: imageView
    // Error parsing type: , name: packImageViewWidthLayoutConstraint
    // Error parsing type: , name: stickerImageViewWidthLayoutConstraint
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak NSLayoutConstraint *stickerImageViewWidthLayoutConstraint; // @synthesize stickerImageViewWidthLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *packImageViewWidthLayoutConstraint; // @synthesize packImageViewWidthLayoutConstraint;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;

@end

