//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers22BaseCollectionViewCell.h"

@class NSLayoutConstraint, UIImageView, _TtC8Stickers18UIImageViewLoading, _TtC8Stickers19UIAspectImageButton;

@interface _TtC8Stickers25StickerCollectionViewCell : _TtC8Stickers22BaseCollectionViewCell
{
    // Error parsing type: , name: stickerImageView
    // Error parsing type: , name: favoriteButton
    // Error parsing type: , name: loadingImageView
    // Error parsing type: , name: stickerImageViewBottomToSuperviewLayoutConstraint
    // Error parsing type: , name: stickerImageViewBottomToFavoritesLayoutConstraint
    // Error parsing type: , name: sticker
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)onFavoriteButton:(id)arg1;
- (void)prepareForReuse;
@property(nonatomic) __weak NSLayoutConstraint *stickerImageViewBottomToFavoritesLayoutConstraint; // @synthesize stickerImageViewBottomToFavoritesLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *stickerImageViewBottomToSuperviewLayoutConstraint; // @synthesize stickerImageViewBottomToSuperviewLayoutConstraint;
@property(nonatomic) __weak _TtC8Stickers18UIImageViewLoading *loadingImageView; // @synthesize loadingImageView;
@property(nonatomic) __weak _TtC8Stickers19UIAspectImageButton *favoriteButton; // @synthesize favoriteButton;
@property(nonatomic) __weak UIImageView *stickerImageView; // @synthesize stickerImageView;

@end

