//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

@class NSString;

@interface _TtC8Stickers16TextFieldEffects : UITextField
{
    // Error parsing type: , name: placeholderLabel
    // Error parsing type: , name: animationCompletionHandler
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)prepareForInterfaceBuilder;
- (void)textFieldDidEndEditing;
- (void)textFieldDidBeginEditing;
- (void)willMoveToSuperview:(id)arg1;
@property(nonatomic, copy) NSString *text;
- (void)drawPlaceholderInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

