//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers24BasicPopUpViewController.h"

@class _TtC8Stickers12UICustomView;

@interface _TtC8Stickers26CustomReviewViewController : _TtC8Stickers24BasicPopUpViewController
{
    // Error parsing type: , name: containerView
    // Error parsing type: , name: onYesHandler
    // Error parsing type: , name: onNoHandler
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onYesButton:(id)arg1;
- (void)onNoButton:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak _TtC8Stickers12UICustomView *containerView; // @synthesize containerView;

@end

