//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers19BasicViewController.h"

@class UILabel;

@interface _TtC8Stickers28MinimalVersionViewController : _TtC8Stickers19BasicViewController
{
    // Error parsing type: , name: messageLabel
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onUpdateButton:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UILabel *messageLabel; // @synthesize messageLabel;

@end

