//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UICollectionView;

@interface _TtC8Stickers19SmallCategoriesView : UIView
{
    // Error parsing type: , name: contentManager
    // Error parsing type: , name: categories
    // Error parsing type: , name: hasInfiniteScroll
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: itemsCount
    // Error parsing type: , name: customDummyCellsCount
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

