//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Stickers18DrawingUndoManager : _TtCs12_SwiftObject
{
    // Error parsing type: , name: onUpdate
    // Error parsing type: , name: snapshots
    // Error parsing type: , name: undoIndex
    // Error parsing type: , name: savingQueue
    // Error parsing type: , name: saveGroup
    // Error parsing type: , name: undoMax
    // Error parsing type: , name: queueLength
    // Error parsing type: , name: queueLengthLimit
    // Error parsing type: , name: overLoaded
}

@end

