//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Stickers33BaseStickerPackCollectionViewCell.h"

@class UIImageView, UILabel, UIStackView, _TtC8Stickers12UICustomView, _TtC8Stickers14UICustomButton, _TtC8Stickers18UIImageViewLoading;

@interface _TtC8Stickers30OriginalPackCollectionViewCell : _TtC8Stickers33BaseStickerPackCollectionViewCell
{
    // Error parsing type: , name: borderView
    // Error parsing type: , name: imageView
    // Error parsing type: , name: downloadNumberLabel
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: loadingImageView
    // Error parsing type: , name: headerStackView
    // Error parsing type: , name: saveStickerPackButton
    // Error parsing type: , name: stripeView
    // Error parsing type: , name: stripeLabel
    // Error parsing type: , name: stickerPack
    // Error parsing type: , name: delegate
    // Error parsing type: , name: heartLabel
}

- (void).cxx_destruct;
- (void)onSaveStickerPackButton:(id)arg1;
- (void)onRefreshCollectionViews:(id)arg1;
- (void)dealloc;
- (void)prepareForReuse;
- (void)awakeFromNib;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak UILabel *stripeLabel; // @synthesize stripeLabel;
@property(nonatomic) __weak _TtC8Stickers12UICustomView *stripeView; // @synthesize stripeView;
@property(nonatomic) __weak _TtC8Stickers14UICustomButton *saveStickerPackButton; // @synthesize saveStickerPackButton;
@property(nonatomic) __weak UIStackView *headerStackView; // @synthesize headerStackView;
@property(nonatomic) __weak _TtC8Stickers18UIImageViewLoading *loadingImageView; // @synthesize loadingImageView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak UILabel *downloadNumberLabel; // @synthesize downloadNumberLabel;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView;
@property(nonatomic) __weak _TtC8Stickers12UICustomView *borderView; // @synthesize borderView;

@end

