//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIImage, _TtC8Stickers25PhotoEditorViewController;

@protocol _TtP8Stickers19PhotoEditorDelegate_
- (void)doneEditingWithPhotoEditor:(_TtC8Stickers25PhotoEditorViewController *)arg1 image:(UIImage *)arg2;

@optional
- (void)canceledEditingWithPhotoEditor:(_TtC8Stickers25PhotoEditorViewController *)arg1;
@end

