//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIView, _TtC8Stickers11WDFlashCard;

@protocol _TtP8Stickers19WDFlashCardDelegate_
- (UIView *)flipBackViewForFlashCard:(_TtC8Stickers11WDFlashCard *)arg1;
- (UIView *)flipFrontViewForFlashCard:(_TtC8Stickers11WDFlashCard *)arg1;

@optional
- (void)flashCardFlippedForFlashCard:(_TtC8Stickers11WDFlashCard *)arg1;
- (void)flashCardWillFlipForFlashCard:(_TtC8Stickers11WDFlashCard *)arg1;
@end

