//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class _TtC8Stickers28ViewControllerKeyboardReturn;

@protocol _TtP8Stickers21BasicKeyboardDelegate_

@optional
- (void)basicKeyboardDidHideWithResult:(_TtC8Stickers28ViewControllerKeyboardReturn *)arg1;
- (void)basicKeyboardDidShowWithResult:(_TtC8Stickers28ViewControllerKeyboardReturn *)arg1;
@end

