//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIImage, UIViewController, _TtC6TCMask6TCMask;

@protocol _TtP6TCMask18TCMaskViewDelegate_

@optional
- (UIViewController *)tcMaskViewWillPushViewControllerWithMask:(_TtC6TCMask6TCMask *)arg1 image:(UIImage *)arg2;
- (void)tcMaskViewDidCompleteWithMask:(_TtC6TCMask6TCMask *)arg1 image:(UIImage *)arg2;
- (void)tcMaskViewDidExitWithMask:(_TtC6TCMask6TCMask *)arg1 image:(UIImage *)arg2;
@end

