//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, _TtC8Stickers14DailyTextField;

@protocol _TtP8Stickers22DailyTextFieldDelegate_
- (void)dailyTextFieldChangedWithSender:(_TtC8Stickers14DailyTextField *)arg1 from:(NSString *)arg2 to:(NSString *)arg3;

@optional
- (void)dailyTextFieldButtonClickedWithSender:(_TtC8Stickers14DailyTextField *)arg1;
@end

