//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, NSURL;

@interface FBAdDSLModel : NSObject
{
    NSURL *_mainHTMLAsset;
    NSURL *_videoLocalAsset;
    NSURL *_imageLocalAsset;
    NSURL *_iconLocalAsset;
    NSMutableArray *_endCardLocalAssets;
    NSString *_title;
    NSString *_subtitle;
    NSString *_body;
    NSString *_callToAction;
    NSString *_socialContext;
    NSString *_ratingValue;
    NSString *_ratingCount;
    NSString *_sponsoredText;
    NSString *_viewabilityCheckInitialDelayMS;
    NSString *_viewabilityCheckIntervalMS;
    NSString *_unskippableSeconds;
}

@property(readonly, nonatomic) NSString *unskippableSeconds; // @synthesize unskippableSeconds=_unskippableSeconds;
@property(readonly, nonatomic) NSString *viewabilityCheckIntervalMS; // @synthesize viewabilityCheckIntervalMS=_viewabilityCheckIntervalMS;
@property(readonly, nonatomic) NSString *viewabilityCheckInitialDelayMS; // @synthesize viewabilityCheckInitialDelayMS=_viewabilityCheckInitialDelayMS;
@property(readonly, nonatomic) NSString *sponsoredText; // @synthesize sponsoredText=_sponsoredText;
@property(readonly, nonatomic) NSString *ratingCount; // @synthesize ratingCount=_ratingCount;
@property(readonly, nonatomic) NSString *ratingValue; // @synthesize ratingValue=_ratingValue;
@property(readonly, nonatomic) NSString *socialContext; // @synthesize socialContext=_socialContext;
@property(readonly, nonatomic) NSString *callToAction; // @synthesize callToAction=_callToAction;
@property(readonly, nonatomic) NSString *body; // @synthesize body=_body;
@property(readonly, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSMutableArray *endCardLocalAssets; // @synthesize endCardLocalAssets=_endCardLocalAssets;
@property(copy, nonatomic) NSURL *iconLocalAsset; // @synthesize iconLocalAsset=_iconLocalAsset;
@property(copy, nonatomic) NSURL *imageLocalAsset; // @synthesize imageLocalAsset=_imageLocalAsset;
@property(copy, nonatomic) NSURL *videoLocalAsset; // @synthesize videoLocalAsset=_videoLocalAsset;
@property(copy, nonatomic) NSURL *mainHTMLAsset; // @synthesize mainHTMLAsset=_mainHTMLAsset;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 callToAction:(id)arg4 socialContext:(id)arg5 ratingValue:(id)arg6 ratingCount:(id)arg7 sponsoredText:(id)arg8 initialDelayMS:(id)arg9 checkIntervalMS:(id)arg10 unskippableSeconds:(id)arg11 endCardSize:(unsigned long long)arg12;

@end

