//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FBBotDetectionBdaasHelpers : NSObject
{
}

+ (void)logEventWithAppSessionId:(id)arg1 eventId:(id)arg2 productType:(unsigned long long)arg3 eventType:(id)arg4 jsonData:(id)arg5 errorDescription:(id)arg6 withLoggerDelegate:(id)arg7 withConfigDelegate:(id)arg8;
+ (void)sendBotDetectionSignalsForEventId:(id)arg1 sessionID:(id)arg2 productType:(unsigned long long)arg3 eventType:(id)arg4 withSignalsDict:(id)arg5 withErrorDict:(id)arg6 withLoggerDelegate:(id)arg7 withConfigDelegate:(id)arg8;

@end

