//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FBSDKMarketingLogger : NSObject
{
}

+ (void)printDebugMessage:(id)arg1;
+ (id)findAbove:(id)arg1;
+ (void)logEvent:(unsigned long long)arg1 paramters:(id)arg2;
+ (void)logEvent:(unsigned long long)arg1 parameters:(id)arg2;
+ (void)logEvent:(unsigned long long)arg1;

@end

