//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSString;
@protocol FIRAuthStorage;

@protocol FIRAuthStorage <NSObject>
- (_Bool)removeDataForKey:(NSString *)arg1 error:(id *)arg2;
- (_Bool)setData:(NSData *)arg1 forKey:(NSString *)arg2 error:(id *)arg3;
- (NSData *)dataForKey:(NSString *)arg1 error:(id *)arg2;
- (id <FIRAuthStorage>)initWithService:(NSString *)arg1;
@end

