//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface FIRActionCodeSettings : NSObject
{
    _Bool _handleCodeInApp;
    _Bool _androidInstallIfNotAvailable;
    NSURL *_URL;
    NSString *_iOSBundleID;
    NSString *_androidPackageName;
    NSString *_androidMinimumVersion;
    NSString *_dynamicLinkDomain;
}

@property(copy, nonatomic) NSString *dynamicLinkDomain; // @synthesize dynamicLinkDomain=_dynamicLinkDomain;
@property(readonly, nonatomic) _Bool androidInstallIfNotAvailable; // @synthesize androidInstallIfNotAvailable=_androidInstallIfNotAvailable;
@property(readonly, copy, nonatomic) NSString *androidMinimumVersion; // @synthesize androidMinimumVersion=_androidMinimumVersion;
@property(readonly, copy, nonatomic) NSString *androidPackageName; // @synthesize androidPackageName=_androidPackageName;
@property(readonly, copy, nonatomic) NSString *iOSBundleID; // @synthesize iOSBundleID=_iOSBundleID;
@property(nonatomic) _Bool handleCodeInApp; // @synthesize handleCodeInApp=_handleCodeInApp;
@property(copy, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;
- (void)setAndroidPackageName:(id)arg1 installIfNotAvailable:(_Bool)arg2 minimumVersion:(id)arg3;
- (void)setIOSBundleID:(id)arg1;
- (id)init;

@end

