//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FIRActionCodeInfo : NSObject
{
    NSString *_email;
    NSString *_fromEmail;
    long long _operation;
}

+ (long long)actionCodeOperationForRequestType:(id)arg1;
@property(readonly, nonatomic) long long operation; // @synthesize operation=_operation;
- (void).cxx_destruct;
- (id)initWithOperation:(long long)arg1 email:(id)arg2 newEmail:(id)arg3;
- (id)dataForKey:(long long)arg1;

@end

