//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FIRAuthDispatcher : NSObject
{
    CDUnknownBlockType _dispatchAfterImplementation;
}

+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType dispatchAfterImplementation; // @synthesize dispatchAfterImplementation=_dispatchAfterImplementation;
- (void).cxx_destruct;
- (void)dispatchAfterDelay:(double)arg1 queue:(id)arg2 task:(CDUnknownBlockType)arg3;

@end

