//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FIRAuthWebUtils : NSObject
{
}

+ (id)parseURL:(id)arg1;
+ (id)stringByUnescapingFromURLArgument:(id)arg1;
+ (id)dictionaryWithHttpArgumentsString:(id)arg1;
+ (id)queryItemValue:(id)arg1 from:(id)arg2;
+ (void)fetchAuthDomainWithRequestConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (_Bool)isExpectedCallbackURL:(id)arg1 eventID:(id)arg2 authType:(id)arg3 callbackScheme:(id)arg4;
+ (_Bool)isCallbackSchemeRegisteredForCustomURLScheme:(id)arg1;
+ (id)randomStringWithLength:(unsigned long long)arg1;
+ (id)supportedAuthDomains;

@end

