//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "WKNavigationDelegate-Protocol.h"

@class FIRAuthWebView, NSString, NSURL;
@protocol FIRAuthWebViewControllerDelegate;

@interface FIRAuthWebViewController : UIViewController <WKNavigationDelegate>
{
    NSURL *_URL;
    id <FIRAuthWebViewControllerDelegate> _delegate;
    FIRAuthWebView *_webView;
}

- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)cancel;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithURL:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

