//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSDictionary, NSString;

@interface FIRAdditionalUserInfo : NSObject <NSSecureCoding>
{
    _Bool _newUser;
    NSString *_providerID;
    NSDictionary *_profile;
    NSString *_username;
}

+ (_Bool)supportsSecureCoding;
+ (id)userInfoWithVerifyAssertionResponse:(id)arg1;
@property(readonly, nonatomic, getter=isNewUser) _Bool newUser; // @synthesize newUser=_newUser;
@property(readonly, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, nonatomic) NSDictionary *profile; // @synthesize profile=_profile;
@property(readonly, nonatomic) NSString *providerID; // @synthesize providerID=_providerID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithProviderID:(id)arg1 profile:(id)arg2 username:(id)arg3 isNewUser:(_Bool)arg4;

@end

