//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FIRAuthRequestConfiguration : NSObject
{
    NSString *_APIKey;
    NSString *_languageCode;
    NSString *_additionalFrameworkMarker;
}

@property(copy, nonatomic) NSString *additionalFrameworkMarker; // @synthesize additionalFrameworkMarker=_additionalFrameworkMarker;
@property(copy, nonatomic) NSString *languageCode; // @synthesize languageCode=_languageCode;
@property(readonly, copy, nonatomic) NSString *APIKey; // @synthesize APIKey=_APIKey;
- (void).cxx_destruct;
- (id)initWithAPIKey:(id)arg1;

@end

