//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FIRAuthKeychainServices, FIRAuthUserDefaults;

@interface FIRAuthStoredUserManager : NSObject
{
    FIRAuthKeychainServices *_keychainServices;
    FIRAuthUserDefaults *_userDefaults;
}

@property(readonly, nonatomic) FIRAuthUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(readonly, nonatomic) FIRAuthKeychainServices *keychainServices; // @synthesize keychainServices=_keychainServices;
- (void).cxx_destruct;
- (_Bool)removeStoredUserForAccessGroup:(id)arg1 projectIdentifier:(id)arg2 error:(id *)arg3;
- (_Bool)setStoredUser:(id)arg1 forAccessGroup:(id)arg2 projectIdentifier:(id)arg3 error:(id *)arg4;
- (id)getStoredUserForAccessGroup:(id)arg1 projectIdentifier:(id)arg2 error:(id *)arg3;
- (_Bool)setStoredUserAccessGroup:(id)arg1 error:(id *)arg2;
- (id)getStoredUserAccessGroupWithError:(id *)arg1;
- (id)initWithServiceName:(id)arg1;

@end

