//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FIRAuthAppCredential, FIRAuthKeychainServices, NSMutableArray, NSMutableDictionary;

@interface FIRAuthAppCredentialManager : NSObject
{
    FIRAuthKeychainServices *_keychainServices;
    NSMutableArray *_pendingReceipts;
    NSMutableDictionary *_callbacksByReceipt;
    FIRAuthAppCredential *_credential;
}

@property(readonly, nonatomic) FIRAuthAppCredential *credential; // @synthesize credential=_credential;
- (void).cxx_destruct;
- (void)callBackWithReceipt:(id)arg1;
- (void)saveData;
- (void)clearCredential;
- (_Bool)canFinishVerificationWithReceipt:(id)arg1 secret:(id)arg2;
- (void)didStartVerificationWithReceipt:(id)arg1 timeout:(double)arg2 callback:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) unsigned long long maximumNumberOfPendingReceipts;
- (id)initWithKeychain:(id)arg1;

@end

