//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FIRQuery.h"

@class FIRDocumentReference, NSString;

@interface FIRCollectionReference : FIRQuery
{
}

- (id)documentWithAutoID;
- (id)addDocumentWithData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)addDocumentWithData:(id)arg1;
- (id)documentWithPath:(id)arg1;
@property(readonly, nonatomic) NSString *path;
@property(readonly, nonatomic) FIRDocumentReference *parent;
@property(readonly, nonatomic) NSString *collectionID;
- (const struct CollectionReference *)reference;
- (unsigned long long)hash;
- (_Bool)isEqualToReference:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithQuery:(struct Query *)arg1;
- (id)initWithPath:(struct ResourcePath)arg1 firestore:(shared_ptr_e3fec009)arg2;
- (id)initWithReference:(struct CollectionReference *)arg1;

@end

