//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FIRQueryDocumentSnapshot;

@interface FIRDocumentChange : NSObject
{
    struct DocumentChange _documentChange;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long newIndex;
@property(readonly, nonatomic) unsigned long long oldIndex;
@property(readonly, nonatomic) FIRQueryDocumentSnapshot *document;
@property(readonly, nonatomic) long long type;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithDocumentChange:(struct DocumentChange *)arg1;

@end

