//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FIRCollectionReference, FIRFirestore, NSString;

@interface FIRDocumentReference : NSObject
{
    struct DocumentReference _documentReference;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (unique_ptr_c03f27e0)wrapDocumentSnapshotBlock:(CDUnknownBlockType)arg1;
- (id)addSnapshotListenerInternalWithOptions:(struct ListenOptions)arg1 listener:(CDUnknownBlockType)arg2;
- (id)addSnapshotListenerWithIncludeMetadataChanges:(_Bool)arg1 listener:(CDUnknownBlockType)arg2;
- (id)addSnapshotListener:(CDUnknownBlockType)arg1;
- (void)getDocumentWithSource:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getDocumentWithCompletion:(CDUnknownBlockType)arg1;
- (void)deleteDocumentWithCompletion:(CDUnknownBlockType)arg1;
- (void)deleteDocument;
- (void)updateData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateData:(id)arg1;
- (void)setData:(id)arg1 mergeFields:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setData:(id)arg1 merge:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setData:(id)arg1 mergeFields:(id)arg2;
- (void)setData:(id)arg1 merge:(_Bool)arg2;
- (void)setData:(id)arg1;
- (id)collectionWithPath:(id)arg1;
@property(readonly, nonatomic) NSString *path;
@property(readonly, nonatomic) FIRCollectionReference *parent;
@property(readonly, nonatomic) NSString *documentID;
@property(readonly, nonatomic) FIRFirestore *firestore; // @dynamic firestore;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithKey:(struct DocumentKey)arg1 firestore:(shared_ptr_e3fec009)arg2;
- (id)initWithPath:(struct ResourcePath)arg1 firestore:(shared_ptr_e3fec009)arg2;
- (id)initWithReference:(struct DocumentReference *)arg1;
- (const struct DocumentKey *)key;
- (const struct DocumentReference *)internalReference;

@end

