//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FIRFieldValue : NSObject
{
}

+ (id)fieldValueForIntegerIncrement:(long long)arg1;
+ (id)fieldValueForDoubleIncrement:(double)arg1;
+ (id)fieldValueForArrayRemove:(id)arg1;
+ (id)fieldValueForArrayUnion:(id)arg1;
+ (id)fieldValueForServerTimestamp;
+ (id)fieldValueForDelete;
- (id)initPrivate;

@end

