//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface FIRFirestoreSettings : NSObject <NSCopying>
{
    _Bool _sslEnabled;
    _Bool _persistenceEnabled;
    _Bool _timestampsInSnapshotsEnabled;
    NSString *_host;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    long long _cacheSizeBytes;
}

@property(nonatomic) long long cacheSizeBytes; // @synthesize cacheSizeBytes=_cacheSizeBytes;
@property(nonatomic, getter=areTimestampsInSnapshotsEnabled) _Bool timestampsInSnapshotsEnabled; // @synthesize timestampsInSnapshotsEnabled=_timestampsInSnapshotsEnabled;
@property(nonatomic, getter=isPersistenceEnabled) _Bool persistenceEnabled; // @synthesize persistenceEnabled=_persistenceEnabled;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(nonatomic, getter=isSSLEnabled) _Bool sslEnabled; // @synthesize sslEnabled=_sslEnabled;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;
- (struct Settings)internalSettings;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)init;

@end

