//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FIRApp, FIRFirestoreSettings, FSTUserDataConverter;
@protocol FSTFirestoreInstanceRegistry;

@interface FIRFirestore : NSObject
{
    shared_ptr_e3fec009 _firestore;
    FIRFirestoreSettings *_settings;
    id <FSTFirestoreInstanceRegistry> _registry;
    FIRApp *_app;
    FSTUserDataConverter *_dataConverter;
}

+ (void)enableLogging:(_Bool)arg1;
+ (id)firestoreForApp:(id)arg1 database:(id)arg2;
+ (id)firestoreForApp:(id)arg1;
+ (id)firestore;
+ (id)recoverFromFirestore:(shared_ptr_e3fec009)arg1;
+ (_Bool)isLoggingEnabled;
@property(readonly, nonatomic) FSTUserDataConverter *dataConverter; // @synthesize dataConverter=_dataConverter;
@property(readonly, nonatomic) FIRApp *app; // @synthesize app=_app;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)terminateWithCompletion:(CDUnknownBlockType)arg1;
- (void)waitForPendingWritesWithCompletion:(CDUnknownBlockType)arg1;
- (void)clearPersistenceWithCompletion:(CDUnknownBlockType)arg1;
- (void)disableNetworkWithCompletion:(CDUnknownBlockType)arg1;
- (void)enableNetworkWithCompletion:(CDUnknownBlockType)arg1;
- (void)runTransactionWithBlock:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runTransactionWithBlock:(CDUnknownBlockType)arg1 dispatchQueue:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)batch;
- (id)collectionGroupWithID:(id)arg1;
- (id)documentWithPath:(id)arg1;
- (id)collectionWithPath:(id)arg1;
@property(copy, nonatomic) FIRFirestoreSettings *settings;
- (id)initWithDatabaseID:(struct DatabaseId)arg1 persistenceKey:(basic_string_90719d97)arg2 credentialsProvider:(shared_ptr_80c12b7c)arg3 workerQueue:(shared_ptr_ada94aa4)arg4 firebaseApp:(id)arg5 instanceRegistry:(id)arg6;
- (void)terminateInternalWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) const struct DatabaseId *databaseID;
- (const shared_ptr_ada94aa4 *)workerQueue;
@property(readonly, nonatomic) shared_ptr_e3fec009 wrapped;

@end

