//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSString, NSURL;

@interface FIRGetAccountInfoResponseUser : NSObject
{
    _Bool _emailVerified;
    NSString *_localID;
    NSString *_email;
    NSString *_displayName;
    NSURL *_photoURL;
    NSDate *_creationDate;
    NSDate *_lastLoginDate;
    NSArray *_providerUserInfo;
    NSString *_passwordHash;
    NSString *_phoneNumber;
}

@property(readonly, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(readonly, nonatomic) NSString *passwordHash; // @synthesize passwordHash=_passwordHash;
@property(readonly, nonatomic) NSArray *providerUserInfo; // @synthesize providerUserInfo=_providerUserInfo;
@property(readonly, nonatomic) NSDate *lastLoginDate; // @synthesize lastLoginDate=_lastLoginDate;
@property(readonly, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(readonly, nonatomic) NSURL *photoURL; // @synthesize photoURL=_photoURL;
@property(readonly, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, nonatomic) _Bool emailVerified; // @synthesize emailVerified=_emailVerified;
@property(readonly, nonatomic) NSString *email; // @synthesize email=_email;
@property(readonly, nonatomic) NSString *localID; // @synthesize localID=_localID;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

