//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FIRAuthCredential.h"

#import "NSSecureCoding-Protocol.h"

@class NSString;

@interface FIROAuthCredential : FIRAuthCredential <NSSecureCoding>
{
    NSString *_IDToken;
    NSString *_accessToken;
    NSString *_secret;
    NSString *_OAuthResponseURLString;
    NSString *_sessionID;
    NSString *_pendingToken;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) NSString *pendingToken; // @synthesize pendingToken=_pendingToken;
@property(readonly, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(readonly, nonatomic) NSString *OAuthResponseURLString; // @synthesize OAuthResponseURLString=_OAuthResponseURLString;
@property(readonly, nonatomic) NSString *secret; // @synthesize secret=_secret;
@property(readonly, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(readonly, nonatomic) NSString *IDToken; // @synthesize IDToken=_IDToken;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)prepareVerifyAssertionRequest:(id)arg1;
- (id)initWithVerifyAssertionResponse:(id)arg1;
- (id)initWithProviderID:(id)arg1 sessionID:(id)arg2 OAuthResponseURLString:(id)arg3;
- (id)initWithProviderID:(id)arg1 IDToken:(id)arg2 accessToken:(id)arg3 secret:(id)arg4 pendingToken:(id)arg5;
- (id)initWithProvider:(id)arg1;

@end

