//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FIRAuthCredential.h"

#import "NSSecureCoding-Protocol.h"

@class NSString;

@interface FIRPhoneAuthCredential : FIRAuthCredential <NSSecureCoding>
{
    NSString *_verificationID;
    NSString *_verificationCode;
    NSString *_temporaryProof;
    NSString *_phoneNumber;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(readonly, nonatomic) NSString *temporaryProof; // @synthesize temporaryProof=_temporaryProof;
@property(readonly, nonatomic) NSString *verificationCode; // @synthesize verificationCode=_verificationCode;
@property(readonly, nonatomic) NSString *verificationID; // @synthesize verificationID=_verificationID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithProviderID:(id)arg1 verificationID:(id)arg2 verificationCode:(id)arg3;
- (id)initWithProvider:(id)arg1;
- (id)initWithTemporaryProof:(id)arg1 phoneNumber:(id)arg2 providerID:(id)arg3;

@end

