//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FIRAuth, NSString;

@interface FIRPhoneAuthProvider : NSObject
{
    FIRAuth *_auth;
    NSString *_callbackScheme;
}

+ (id)providerWithAuth:(id)arg1;
+ (id)provider;
- (void).cxx_destruct;
- (void)reCAPTCHAURLWithEventID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reCAPTCHAFlowWithUIDelegate:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)verifyClientWithUIDelegate:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)verifyClientAndSendVerificationCodeToPhoneNumber:(id)arg1 retryOnInvalidAppCredential:(_Bool)arg2 UIDelegate:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)internalVerifyPhoneNumber:(id)arg1 UIDelegate:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)reCAPTCHATokenForURL:(id)arg1 error:(id *)arg2;
- (id)credentialWithVerificationID:(id)arg1 verificationCode:(id)arg2;
- (void)verifyPhoneNumber:(id)arg1 UIDelegate:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithAuth:(id)arg1;

@end

