//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FIRQuery, FIRSnapshotMetadata, NSArray;

@interface FIRQuerySnapshot : NSObject
{
    struct DelayedConstructor<firebase::firestore::api::QuerySnapshot> _snapshot;
    FIRSnapshotMetadata *_cached_metadata;
    NSArray *_documents;
    NSArray *_documentChanges;
    _Bool _documentChangesIncludeMetadataChanges;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)documentChangesWithIncludeMetadataChanges:(_Bool)arg1;
@property(readonly, nonatomic) NSArray *documentChanges;
@property(readonly, nonatomic) NSArray *documents;
@property(readonly, nonatomic) long long count;
@property(readonly, nonatomic, getter=isEmpty) _Bool empty; // @dynamic empty;
@property(readonly, nonatomic) FIRSnapshotMetadata *metadata;
@property(readonly, nonatomic) FIRQuery *query;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithFirestore:(shared_ptr_e3fec009)arg1 originalQuery:(struct Query)arg2 snapshot:(struct ViewSnapshot *)arg3 metadata:(struct SnapshotMetadata)arg4;
- (id)initWithSnapshot:(struct QuerySnapshot *)arg1;

@end

