//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FIRIdentityToolkitRequest.h"

#import "FIRAuthRPCRequest-Protocol.h"

@class NSArray, NSString, NSURL;

@interface FIRSetAccountInfoRequest : FIRIdentityToolkitRequest <FIRAuthRPCRequest>
{
    _Bool _emailVerified;
    _Bool _upgradeToFederatedLogin;
    _Bool _returnSecureToken;
    NSString *_accessToken;
    NSString *_displayName;
    NSString *_localID;
    NSString *_email;
    NSURL *_photoURL;
    NSString *_password;
    NSArray *_providers;
    NSString *_OOBCode;
    NSString *_captchaChallenge;
    NSString *_captchaResponse;
    NSArray *_deleteAttributes;
    NSArray *_deleteProviders;
}

@property(nonatomic) _Bool returnSecureToken; // @synthesize returnSecureToken=_returnSecureToken;
@property(copy, nonatomic) NSArray *deleteProviders; // @synthesize deleteProviders=_deleteProviders;
@property(copy, nonatomic) NSArray *deleteAttributes; // @synthesize deleteAttributes=_deleteAttributes;
@property(copy, nonatomic) NSString *captchaResponse; // @synthesize captchaResponse=_captchaResponse;
@property(copy, nonatomic) NSString *captchaChallenge; // @synthesize captchaChallenge=_captchaChallenge;
@property(nonatomic) _Bool upgradeToFederatedLogin; // @synthesize upgradeToFederatedLogin=_upgradeToFederatedLogin;
@property(nonatomic) _Bool emailVerified; // @synthesize emailVerified=_emailVerified;
@property(copy, nonatomic) NSString *OOBCode; // @synthesize OOBCode=_OOBCode;
@property(copy, nonatomic) NSArray *providers; // @synthesize providers=_providers;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSURL *photoURL; // @synthesize photoURL=_photoURL;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(copy, nonatomic) NSString *localID; // @synthesize localID=_localID;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
- (void).cxx_destruct;
- (id)unencodedHTTPRequestBodyWithError:(id *)arg1;
- (id)initWithRequestConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

