//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FIRStorageObservableTask.h"

#import "FIRStorageTaskManagement-Protocol.h"
#import "SDWebImageOperation-Protocol.h"

@class GTMSessionFetcher, NSData, NSProgress, NSString, NSURL;

@interface FIRStorageDownloadTask : FIRStorageObservableTask <SDWebImageOperation, FIRStorageTaskManagement>
{
    NSProgress *_progress;
    GTMSessionFetcher *_fetcher;
    CDUnknownBlockType _fetcherCompletion;
    NSData *_downloadData;
    NSURL *_fileURL;
}

@property(copy, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
@property(readonly, nonatomic) NSData *downloadData; // @synthesize downloadData=_downloadData;
- (CDUnknownBlockType)fetcherCompletion;
- (void)setFetcher:(id)arg1;
- (id)fetcher;
- (void)setProgress:(id)arg1;
- (id)progress;
- (void).cxx_destruct;
- (void)resume;
- (void)pause;
- (void)cancelWithError:(id)arg1;
- (void)cancel;
- (void)enqueueWithData:(id)arg1;
- (void)enqueue;
- (void)dealloc;
- (id)initWithReference:(id)arg1 fetcherService:(id)arg2 dispatchQueue:(id)arg3 file:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

