//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FIRIdentityToolkitRequest.h"

#import "FIRAuthRPCRequest-Protocol.h"

@class FIRAuthAppCredential, NSString;

@interface FIRSendVerificationCodeRequest : FIRIdentityToolkitRequest <FIRAuthRPCRequest>
{
    NSString *_phoneNumber;
    FIRAuthAppCredential *_appCredential;
    NSString *_reCAPTCHAToken;
}

@property(readonly, nonatomic) NSString *reCAPTCHAToken; // @synthesize reCAPTCHAToken=_reCAPTCHAToken;
@property(readonly, nonatomic) FIRAuthAppCredential *appCredential; // @synthesize appCredential=_appCredential;
@property(readonly, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
- (void).cxx_destruct;
- (id)unencodedHTTPRequestBodyWithError:(id *)arg1;
- (id)initWithPhoneNumber:(id)arg1 appCredential:(id)arg2 reCAPTCHAToken:(id)arg3 requestConfiguration:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

