//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FIRSnapshotMetadata : NSObject
{
    struct SnapshotMetadata _metadata;
}

- (id).cxx_construct;
@property(readonly, nonatomic, getter=isFromCache) _Bool fromCache;
@property(readonly, nonatomic, getter=hasPendingWrites) _Bool pendingWrites;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithPendingWrites:(_Bool)arg1 fromCache:(_Bool)arg2;
- (id)initWithMetadata:(struct SnapshotMetadata)arg1;

@end

