//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FIRAuthRPCRequest-Protocol.h"

@class FIRAuthRequestConfiguration, NSString;

@interface FIRSecureTokenRequest : NSObject <FIRAuthRPCRequest>
{
    FIRAuthRequestConfiguration *_requestConfiguration;
    unsigned long long _grantType;
    NSString *_scope;
    NSString *_refreshToken;
    NSString *_code;
    NSString *_APIKey;
}

+ (void)setHost:(id)arg1;
+ (id)host;
+ (id)grantTypeStringWithGrantType:(unsigned long long)arg1;
+ (id)refreshRequestWithRefreshToken:(id)arg1 requestConfiguration:(id)arg2;
+ (id)authCodeRequestWithCode:(id)arg1 requestConfiguration:(id)arg2;
@property(readonly, copy, nonatomic) NSString *APIKey; // @synthesize APIKey=_APIKey;
@property(readonly, copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(readonly, copy, nonatomic) NSString *refreshToken; // @synthesize refreshToken=_refreshToken;
@property(readonly, copy, nonatomic) NSString *scope; // @synthesize scope=_scope;
@property(readonly, nonatomic) unsigned long long grantType; // @synthesize grantType=_grantType;
- (void).cxx_destruct;
- (id)unencodedHTTPRequestBodyWithError:(id *)arg1;
- (_Bool)containsPostBody;
- (id)requestURL;
- (id)requestConfiguration;
- (id)initWithGrantType:(unsigned long long)arg1 scope:(id)arg2 refreshToken:(id)arg3 code:(id)arg4 requestConfiguration:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

