//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FIRAuthRPCResponse-Protocol.h"

@class NSString;

@interface FIRSendVerificationCodeResponse : NSObject <FIRAuthRPCResponse>
{
    NSString *_verificationID;
}

@property(readonly, nonatomic) NSString *verificationID; // @synthesize verificationID=_verificationID;
- (void).cxx_destruct;
- (_Bool)setWithDictionary:(id)arg1 error:(id *)arg2;
- (id)expectedKind;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

