//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FIRFirestore;

@interface FIRTransaction : NSObject
{
    shared_ptr_1e1d82c1 _internalTransaction;
    FIRFirestore *_firestore;
}

+ (id)transactionWithInternalTransaction:(shared_ptr_1e1d82c1)arg1 firestore:(id)arg2;
@property(readonly, nonatomic) FIRFirestore *firestore; // @synthesize firestore=_firestore;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)validateReference:(id)arg1;
- (id)getDocument:(id)arg1 error:(id *)arg2;
- (void)getDocument:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)deleteDocument:(id)arg1;
- (id)updateData:(id)arg1 forDocument:(id)arg2;
- (id)setData:(id)arg1 forDocument:(id)arg2 mergeFields:(id)arg3;
- (id)setData:(id)arg1 forDocument:(id)arg2 merge:(_Bool)arg3;
- (id)setData:(id)arg1 forDocument:(id)arg2;
- (id)initWithTransaction:(shared_ptr_1e1d82c1)arg1 firestore:(id)arg2;

@end

