//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FIRUserInfo-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class FIRAuth, FIRAuthRequestConfiguration, FIRAuthSerialTaskQueue, FIRSecureTokenService, FIRUserMetadata, NSArray, NSDate, NSDictionary, NSString, NSURL;

@interface FIRUser : NSObject <NSSecureCoding, FIRUserInfo>
{
    _Bool _hasEmailPasswordCredential;
    NSDictionary *_providerData;
    FIRAuthSerialTaskQueue *_taskQueue;
    FIRSecureTokenService *_tokenService;
    _Bool _anonymous;
    _Bool _emailVerified;
    NSString *_userID;
    NSString *_displayName;
    NSURL *_photoURL;
    NSString *_email;
    NSString *_phoneNumber;
    FIRUserMetadata *_metadata;
    FIRAuth *_auth;
    FIRAuthRequestConfiguration *_requestConfiguration;
}

+ (_Bool)supportsSecureCoding;
+ (void)retrieveUserWithAuth:(id)arg1 accessToken:(id)arg2 accessTokenExpirationDate:(id)arg3 refreshToken:(id)arg4 anonymous:(_Bool)arg5 callback:(CDUnknownBlockType)arg6;
@property(retain, nonatomic) FIRAuthRequestConfiguration *requestConfiguration; // @synthesize requestConfiguration=_requestConfiguration;
@property(nonatomic) __weak FIRAuth *auth; // @synthesize auth=_auth;
@property(readonly, nonatomic) FIRUserMetadata *metadata; // @synthesize metadata=_metadata;
@property(readonly, nonatomic, getter=isEmailVerified) _Bool emailVerified; // @synthesize emailVerified=_emailVerified;
@property(nonatomic, getter=isAnonymous) _Bool anonymous; // @synthesize anonymous=_anonymous;
@property(readonly, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(readonly, copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(readonly, copy, nonatomic) NSURL *photoURL; // @synthesize photoURL=_photoURL;
@property(readonly, copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, copy, nonatomic) NSString *uid; // @synthesize uid=_userID;
- (void).cxx_destruct;
- (void)signOutIfTokenIsInvalidWithError:(id)arg1;
- (void)deleteWithCompletion:(CDUnknownBlockType)arg1;
- (void)sendEmailVerificationWithNullableActionCodeSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)sendEmailVerificationWithActionCodeSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)sendEmailVerificationWithCompletion:(CDUnknownBlockType)arg1;
- (void)unlinkFromProvider:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)linkAndRetrieveDataWithCredential:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)linkWithCredential:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)internalVerifyBeforeUpdateEmailWithNewEmail:(id)arg1 actionCodeSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)internalGetTokenForcingRefresh:(_Bool)arg1 callback:(CDUnknownBlockType)arg2;
- (void)internalGetTokenWithCallback:(CDUnknownBlockType)arg1;
- (id)parseIDToken:(id)arg1 error:(id *)arg2;
- (void)getIDTokenResultForcingRefresh:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getIDTokenResultWithCompletion:(CDUnknownBlockType)arg1;
- (void)getIDTokenForcingRefresh:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getIDTokenWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSString *refreshToken;
- (void)reauthenticateAndRetrieveDataWithCredential:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reauthenticateWithCredential:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reloadWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly, copy, nonatomic) NSDate *accessTokenExpirationDate;
@property(readonly, copy, nonatomic) NSString *rawAccessToken;
- (void)setPhotoURL:(id)arg1;
- (void)setDisplayName:(id)arg1;
- (id)profileChangeRequest;
- (void)updatePhoneNumberCredential:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)internalUpdateOrLinkPhoneNumberCredential:(id)arg1 isLinkOperation:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updatePassword:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateEmail:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateEmail:(id)arg1 password:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)setTokenService:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (_Bool)updateKeychain:(id *)arg1;
- (void)executeUserUpdateWithChanges:(CDUnknownBlockType)arg1 callback:(CDUnknownBlockType)arg2;
- (void)updateWithGetAccountInfoResponse:(id)arg1;
- (void)getAccountInfoRefreshingCache:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSArray *providerData;
@property(readonly, copy, nonatomic) NSString *providerID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithTokenService:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

