//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FIRUser, NSString, NSURL;

@interface FIRUserProfileChangeRequest : NSObject
{
    FIRUser *_user;
    NSString *_displayName;
    _Bool _displayNameSet;
    NSURL *_photoURL;
    _Bool _photoURLSet;
    _Bool _consumed;
}

- (void).cxx_destruct;
- (void)commitChangesWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)hasUpdates;
@property(copy, nonatomic) NSURL *photoURL;
@property(copy, nonatomic) NSString *displayName;
- (id)initWithUser:(id)arg1;

@end

