//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FIRIdentityToolkitRequest.h"

#import "FIRAuthRPCRequest-Protocol.h"

@class NSString;

@interface FIRVerifyPasswordRequest : FIRIdentityToolkitRequest <FIRAuthRPCRequest>
{
    _Bool _returnSecureToken;
    NSString *_email;
    NSString *_password;
    NSString *_pendingIDToken;
    NSString *_captchaChallenge;
    NSString *_captchaResponse;
}

@property(nonatomic) _Bool returnSecureToken; // @synthesize returnSecureToken=_returnSecureToken;
@property(copy, nonatomic) NSString *captchaResponse; // @synthesize captchaResponse=_captchaResponse;
@property(copy, nonatomic) NSString *captchaChallenge; // @synthesize captchaChallenge=_captchaChallenge;
@property(copy, nonatomic) NSString *pendingIDToken; // @synthesize pendingIDToken=_pendingIDToken;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
- (void).cxx_destruct;
- (id)unencodedHTTPRequestBodyWithError:(id *)arg1;
- (id)initWithEmail:(id)arg1 password:(id)arg2 requestConfiguration:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

