//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FSTUserDataConverter;

@interface FIRWriteBatch : NSObject
{
    struct DelayedConstructor<firebase::firestore::api::WriteBatch> _writeBatch;
    FSTUserDataConverter *_dataConverter;
}

+ (id)writeBatchWithDataConverter:(id)arg1 writeBatch:(struct WriteBatch *)arg2;
@property(readonly, nonatomic) FSTUserDataConverter *dataConverter; // @synthesize dataConverter=_dataConverter;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)commitWithCompletion:(CDUnknownBlockType)arg1;
- (void)commit;
- (id)deleteDocument:(id)arg1;
- (id)updateData:(id)arg1 forDocument:(id)arg2;
- (id)setData:(id)arg1 forDocument:(id)arg2 mergeFields:(id)arg3;
- (id)setData:(id)arg1 forDocument:(id)arg2 merge:(_Bool)arg3;
- (id)setData:(id)arg1 forDocument:(id)arg2;
- (id)initWithDataConverter:(id)arg1 writeBatch:(struct WriteBatch *)arg2;

@end

