//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

#import "FNFPlayerDisplayLayer-Protocol.h"

@class NSString;
@protocol FNFAVPlayer, FNFPlayerDisplayLayerDelegate;

@interface FNFPlayerIOSurfaceLayer : CALayer <FNFPlayerDisplayLayer>
{
    long long _preferredConversion;
    double _preferredRotation;
    struct CGAffineTransform _preferredTransform;
    NSString *_videoGravity;
    struct CGSize _presentationSize;
    struct CGSize _layerSize;
    _Bool _isReadyForDisplay;
    _Bool _layoutChanged;
    id <FNFPlayerDisplayLayerDelegate> _displayLayerDelegate;
}

@property(nonatomic) __weak id <FNFPlayerDisplayLayerDelegate> displayLayerDelegate; // @synthesize displayLayerDelegate=_displayLayerDelegate;
- (void).cxx_destruct;
- (void)_updateReadyForDisplay:(_Bool)arg1;
- (void)_drawFrame:(_Bool)arg1 preventPlayback:(_Bool)arg2;
@property(nonatomic) struct CGAffineTransform preferredTransform;
@property(readonly, nonatomic, getter=isReadyForDisplay) _Bool readyForDisplay;
@property(copy, nonatomic) NSString *videoGravity;
@property(readonly, nonatomic) struct CGSize presentationSize;
@property(retain, nonatomic) id <FNFAVPlayer> player;
- (void)resetRendering;
- (void)clearBuffers;
- (void)flushDisplayLayer:(_Bool)arg1;
- (void)updateDisplayLayer;
- (void)displayEmptyBuffer:(_Bool)arg1 preventPlayback:(_Bool)arg2 lastDisplayedSampleBuffer:(struct __CVBuffer *)arg3;
- (void)displayPixelBuffer:(struct __CVBuffer *)arg1 preventPlayback:(_Bool)arg2;
- (void)initializeDisplayLayer;
- (void)setRenderer:(id)arg1;
- (void)layoutSublayers;
- (id)initWithConfig:(CDStruct_b6254f9e)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

