//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FSTDocumentKeyReference : NSObject
{
    struct DocumentKey _key;
    struct DatabaseId _databaseID;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) const struct DatabaseId *databaseID;
- (const struct DocumentKey *)key;
- (id)initWithKey:(struct DocumentKey)arg1 databaseID:(struct DatabaseId)arg2;

@end

