//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FSTLRUDelegate-Protocol.h"
#import "FSTReferenceDelegate-Protocol.h"

@class FSTLevelDB, NSString;

@interface FSTLevelDBLRUDelegate : NSObject <FSTReferenceDelegate, FSTLRUDelegate>
{
    struct LruDelegateBridge _delegateBridge;
    struct unique_ptr<firebase::firestore::local::LruGarbageCollector, std::__1::default_delete<firebase::firestore::local::LruGarbageCollector>> _gc;
    FSTLevelDB *_db;
    struct ReferenceSet *_additionalReferences;
    long long _currentSequenceNumber;
    struct unique_ptr<firebase::firestore::local::ListenSequence, std::__1::default_delete<firebase::firestore::local::ListenSequence>> _listenSequence;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned long long)byteSize;
- (void)limboDocumentUpdated:(const struct DocumentKey *)arg1;
- (void)removeMutationReference:(const struct DocumentKey *)arg1;
- (void)writeSentinelForKey:(const struct DocumentKey *)arg1;
- (struct LruGarbageCollector *)gc;
- (unsigned long long)sequenceNumberCount;
- (int)removeTargetsThroughSequenceNumber:(long long)arg1 liveQueries:(const struct unordered_map<int, firebase::firestore::local::QueryData, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, firebase::firestore::local::QueryData>>> *)arg2;
- (void)removeSentinel:(const struct DocumentKey *)arg1;
- (int)removeOrphanedDocumentsThroughSequenceNumber:(long long)arg1;
- (void)enumerateMutationsUsingCallback:(const function_9a8728a7 *)arg1;
- (void)enumerateTargetsUsingCallback:(const struct function<void (const firebase::firestore::local::QueryData &)> *)arg1;
- (_Bool)isPinned:(const struct DocumentKey *)arg1;
- (_Bool)mutationQueuesContainKey:(const struct DocumentKey *)arg1;
- (void)removeReference:(const struct DocumentKey *)arg1;
- (void)addReference:(const struct DocumentKey *)arg1;
- (void)removeTarget:(const struct QueryData *)arg1;
- (void)addInMemoryPins:(struct ReferenceSet *)arg1;
@property(readonly, nonatomic) long long currentSequenceNumber;
- (void)transactionWillCommit;
- (void)transactionWillStart;
- (void)start;
- (id)initWithPersistence:(id)arg1 lruParams:(struct LruParams)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

