//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol FSTLRUDelegate
- (struct LruGarbageCollector *)gc;
- (unsigned long long)sequenceNumberCount;
- (unsigned long long)byteSize;
- (int)removeTargetsThroughSequenceNumber:(long long)arg1 liveQueries:(const struct unordered_map<int, firebase::firestore::local::QueryData, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, firebase::firestore::local::QueryData>>> *)arg2;
- (int)removeOrphanedDocumentsThroughSequenceNumber:(long long)arg1;
- (void)enumerateMutationsUsingCallback:(const function_9a8728a7 *)arg1;
- (void)enumerateTargetsUsingCallback:(const struct function<void (const firebase::firestore::local::QueryData &)> *)arg1;
@end

