//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol FSTPersistence;

@interface FSTLocalStore : NSObject
{
    struct TargetIdGenerator _targetIDGenerator;
    struct RemoteDocumentCache *_remoteDocumentCache;
    struct QueryCache *_queryCache;
    struct MutationQueue *_mutationQueue;
    struct unique_ptr<firebase::firestore::local::LocalDocumentsView, std::__1::default_delete<firebase::firestore::local::LocalDocumentsView>> _localDocuments;
    struct ReferenceSet _localViewReferences;
    struct unordered_map<int, firebase::firestore::local::QueryData, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, firebase::firestore::local::QueryData>>> _targetIDs;
    id <FSTPersistence> _persistence;
}

@property(nonatomic) struct QueryCache *queryCache; // @synthesize queryCache=_queryCache;
@property(readonly, nonatomic) id <FSTPersistence> persistence; // @synthesize persistence=_persistence;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct LruResults)collectGarbage:(struct LruGarbageCollector *)arg1;
- (void)applyBatchResult:(const struct MutationBatchResult *)arg1;
- (SortedSet_8472c2f7)remoteDocumentKeysForTarget:(int)arg1;
- (struct DocumentMap)executeQuery:(const struct Query *)arg1;
- (void)releaseQuery:(const struct Query *)arg1;
- (struct QueryData)allocateQuery:(struct Query)arg1;
- (int)getHighestUnacknowledgedBatchId;
- (optional_da0b7706)readDocument:(const struct DocumentKey *)arg1;
- (optional_976868b1)nextMutationBatchAfterBatchID:(int)arg1;
- (void)notifyLocalViewChanges:(const vector_c8ba1e59 *)arg1;
- (_Bool)shouldPersistQueryData:(const struct QueryData *)arg1 oldQueryData:(const struct QueryData *)arg2 change:(const struct TargetChange *)arg3;
- (SortedMap_4bc8f18e)applyRemoteEvent:(const struct RemoteEvent *)arg1;
- (const struct SnapshotVersion *)lastRemoteSnapshotVersion;
- (void)setLastStreamToken:(const struct ByteString *)arg1;
- (struct ByteString)lastStreamToken;
- (SortedMap_4bc8f18e)rejectBatchID:(int)arg1;
- (SortedMap_4bc8f18e)acknowledgeBatchWithResult:(const struct MutationBatchResult *)arg1;
- (struct LocalWriteResult)locallyWriteMutations:(vector_ea6b9d7e *)arg1;
- (SortedMap_4bc8f18e)userDidChange:(const struct User *)arg1;
- (void)startMutationQueue;
- (void)start;
- (id)initWithPersistence:(id)arg1 initialUser:(const struct User *)arg2;

@end

