//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FSTPersistence-Protocol.h"
#import "FSTTransactional-Protocol.h"

@class FSTLevelDBLRUDelegate, FSTLocalSerializer, NSString;

@interface FSTLevelDB : NSObject <FSTPersistence, FSTTransactional>
{
    struct Path _directory;
    struct unique_ptr<firebase::firestore::local::LevelDbTransaction, std::__1::default_delete<firebase::firestore::local::LevelDbTransaction>> _transaction;
    unique_ptr_b0135d45 _ptr;
    struct unique_ptr<firebase::firestore::local::LevelDbRemoteDocumentCache, std::__1::default_delete<firebase::firestore::local::LevelDbRemoteDocumentCache>> _documentCache;
    struct unique_ptr<firebase::firestore::local::LevelDbIndexManager, std::__1::default_delete<firebase::firestore::local::LevelDbIndexManager>> _indexManager;
    struct FSTTransactionRunner _transactionRunner;
    FSTLevelDBLRUDelegate *_referenceDelegate;
    struct unique_ptr<firebase::firestore::local::LevelDbQueryCache, std::__1::default_delete<firebase::firestore::local::LevelDbQueryCache>> _queryCache;
    set_0cfa92bf _users;
    struct unique_ptr<firebase::firestore::local::LevelDbMutationQueue, std::__1::default_delete<firebase::firestore::local::LevelDbMutationQueue>> _currentMutationQueue;
    _Bool _started;
    FSTLocalSerializer *_serializer;
}

+ (StatusOr_cee8aa85)createDBWithDirectory:(const struct Path *)arg1;
+ (struct Status)ensureDirectory:(const struct Path *)arg1;
+ (struct Path)storageDirectoryForDatabaseInfo:(const struct DatabaseInfo *)arg1 documentsDirectory:(const struct Path *)arg2;
+ (struct Path)documentsDirectory;
+ (struct Status)clearPersistence:(const struct DatabaseInfo *)arg1;
+ (struct Status)dbWithDirectory:(struct Path)arg1 serializer:(id)arg2 lruParams:(struct LruParams)arg3 ptr:(id *)arg4;
+ (set_0cfa92bf)collectUserSet:(struct LevelDbTransaction *)arg1;
+ (struct ReadOptions)standardReadOptions;
@property(nonatomic, getter=isStarted) _Bool started; // @synthesize started=_started;
@property(readonly, nonatomic) FSTLocalSerializer *serializer; // @synthesize serializer=_serializer;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long currentSequenceNumber;
@property(readonly, nonatomic) FSTLevelDBLRUDelegate *referenceDelegate;
- (void)shutdown;
- (void)commitTransaction;
- (void)startTransaction:(struct string_view)arg1;
- (struct IndexManager *)indexManager;
- (struct RemoteDocumentCache *)remoteDocumentCache;
- (struct LevelDbQueryCache *)queryCache;
- (struct LevelDbMutationQueue *)mutationQueueForUser:(const struct User *)arg1;
@property(readonly, nonatomic) struct LevelDbTransaction *currentTransaction;
@property(readonly, nonatomic) const struct FSTTransactionRunner *run;
@property(readonly, nonatomic) struct DB *ptr;
@property(readonly, nonatomic) const set_0cfa92bf *users;
- (unsigned long long)byteSize;
- (id)initWithLevelDB:(unique_ptr_b0135d45)arg1 users:(set_0cfa92bf)arg2 directory:(struct Path)arg3 serializer:(id)arg4 lruParams:(struct LruParams)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

