//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FSTSerializerBeta;

@interface FSTLocalSerializer : NSObject
{
    FSTSerializerBeta *_remoteSerializer;
}

@property(readonly, nonatomic) FSTSerializerBeta *remoteSerializer; // @synthesize remoteSerializer=_remoteSerializer;
- (void).cxx_destruct;
- (struct SnapshotVersion)decodedVersion:(id)arg1;
- (id)encodedVersion:(const struct SnapshotVersion *)arg1;
- (struct QueryData)decodedQueryData:(id)arg1;
- (id)encodedQueryData:(const struct QueryData *)arg1;
- (struct MutationBatch)decodedMutationBatch:(id)arg1;
- (id)encodedMutationBatch:(const struct MutationBatch *)arg1;
- (struct UnknownDocument)decodedUnknownDocument:(id)arg1;
- (id)encodedUnknownDocument:(const struct UnknownDocument *)arg1;
- (struct NoDocument)decodedDeletedDocument:(id)arg1 withCommittedMutations:(_Bool)arg2;
- (id)encodedDeletedDocument:(const struct NoDocument *)arg1;
- (struct Document)decodedDocument:(id)arg1 withCommittedMutations:(_Bool)arg2;
- (id)encodedDocument:(const struct Document *)arg1;
- (struct MaybeDocument)decodedMaybeDocument:(id)arg1;
- (id)encodedMaybeDocument:(const struct MaybeDocument *)arg1;
- (id)initWithRemoteSerializer:(id)arg1;

@end

