//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FSTPersistence-Protocol.h"

@class NSString;
@protocol FSTReferenceDelegate;

@interface FSTMemoryPersistence : NSObject <FSTPersistence>
{
    struct unique_ptr<firebase::firestore::local::MemoryQueryCache, std::__1::default_delete<firebase::firestore::local::MemoryQueryCache>> _queryCache;
    struct unique_ptr<firebase::firestore::local::MemoryRemoteDocumentCache, std::__1::default_delete<firebase::firestore::local::MemoryRemoteDocumentCache>> _remoteDocumentCache;
    struct MemoryIndexManager _indexManager;
    struct FSTTransactionRunner _transactionRunner;
    id <FSTReferenceDelegate> _referenceDelegate;
    _Bool _started;
    unordered_map_9e1c1e20 _mutationQueues;
}

+ (id)persistenceWithLruParams:(struct LruParams)arg1 serializer:(id)arg2;
+ (id)persistenceWithEagerGC;
@property(nonatomic, getter=isStarted) _Bool started; // @synthesize started=_started;
@property(readonly, nonatomic) unordered_map_9e1c1e20 *mutationQueues; // @synthesize mutationQueues=_mutationQueues;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct MemoryIndexManager *)indexManager;
- (struct MemoryRemoteDocumentCache *)remoteDocumentCache;
- (struct MemoryQueryCache *)queryCache;
- (struct MemoryMutationQueue *)mutationQueueForUser:(const struct User *)arg1;
@property(readonly, nonatomic) const struct FSTTransactionRunner *run;
@property(readonly, nonatomic) long long currentSequenceNumber;
@property(retain, nonatomic) id <FSTReferenceDelegate> referenceDelegate;
- (void)shutdown;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

