//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol FSTReferenceDelegate;

@protocol FSTPersistence <NSObject>
@property(readonly, nonatomic) long long currentSequenceNumber;
@property(readonly, nonatomic) id <FSTReferenceDelegate> referenceDelegate;
@property(readonly, nonatomic) const struct FSTTransactionRunner *run;
- (struct IndexManager *)indexManager;
- (struct RemoteDocumentCache *)remoteDocumentCache;
- (struct QueryCache *)queryCache;
- (struct MutationQueue *)mutationQueueForUser:(const struct User *)arg1;
- (void)shutdown;
@end

