//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FSTQueryView : NSObject
{
    Query_9db663f1 _query;
    struct ByteString _resumeToken;
    struct DelayedConstructor<firebase::firestore::core::View> _view;
    int _targetID;
}

@property(readonly, nonatomic) int targetID; // @synthesize targetID=_targetID;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct View *)view;
- (const struct ByteString *)resumeToken;
- (const struct Query *)query;
- (id)initWithQuery:(struct Query)arg1 targetID:(int)arg2 resumeToken:(struct ByteString)arg3 view:(struct View)arg4;

@end

