//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol FSTReferenceDelegate <NSObject>
@property(readonly, nonatomic) long long currentSequenceNumber;
- (void)limboDocumentUpdated:(const struct DocumentKey *)arg1;
- (void)removeMutationReference:(const struct DocumentKey *)arg1;
- (void)removeReference:(const struct DocumentKey *)arg1;
- (void)addReference:(const struct DocumentKey *)arg1;
- (void)removeTarget:(const struct QueryData *)arg1;
- (void)addInMemoryPins:(struct ReferenceSet *)arg1;
@end

