//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSError;

@protocol FSTRemoteSyncer
- (SortedSet_8472c2f7)remoteKeysForTarget:(int)arg1;
- (void)rejectFailedWriteWithBatchID:(int)arg1 error:(NSError *)arg2;
- (void)applySuccessfulWriteWithResult:(const struct MutationBatchResult *)arg1;
- (void)rejectListenWithTargetID:(int)arg1 error:(NSError *)arg2;
- (void)applyRemoteEvent:(const struct RemoteEvent *)arg1;
@end

