//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SDImageLoader-Protocol.h"

@class NSString;

@interface FUIStorageImageLoader : NSObject <SDImageLoader>
{
    unsigned long long _defaultMaxImageSize;
}

+ (id)sharedLoader;
@property(nonatomic) unsigned long long defaultMaxImageSize; // @synthesize defaultMaxImageSize=_defaultMaxImageSize;
- (_Bool)shouldBlockFailedURLWithURL:(id)arg1 error:(id)arg2;
- (id)requestImageWithURL:(id)arg1 options:(unsigned long long)arg2 context:(struct NSDictionary *)arg3 progress:(CDUnknownBlockType)arg4 completed:(CDUnknownBlockType)arg5;
- (_Bool)canRequestImageForURL:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

