//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBAdView, GADFBAdapterDelegate;
@protocol GADMAdNetworkAdapter, GADMAdNetworkConnector;

@interface GADFBBannerAd : NSObject
{
    id <GADMAdNetworkConnector> _connector;
    id <GADMAdNetworkAdapter> _adapter;
    FBAdView *_bannerAd;
    GADFBAdapterDelegate *_adapterDelegate;
}

- (void).cxx_destruct;
- (void)stopBeingDelegate;
- (void)getBannerWithSize:(struct GADAdSize)arg1;
- (id)init;
- (id)initWithGADMAdNetworkConnector:(id)arg1 adapter:(id)arg2;

@end

