//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBRewardedVideoAdDelegate-Protocol.h"
#import "GADMediationRewardedAd-Protocol.h"

@class FBRewardedVideoAd, NSString;
@protocol GADMediationRewardedAdEventDelegate;

@interface GADFBRewardedRenderer : NSObject <GADMediationRewardedAd, FBRewardedVideoAdDelegate>
{
    CDUnknownBlockType _adLoadCompletionHandler;
    FBRewardedVideoAd *_rewardedAd;
    id <GADMediationRewardedAdEventDelegate> _adEventDelegate;
    _Bool _isRTBRequest;
}

- (void).cxx_destruct;
- (void)presentFromViewController:(id)arg1;
- (void)rewardedVideoAdWillLogImpression:(id)arg1;
- (void)rewardedVideoAdVideoComplete:(id)arg1;
- (void)rewardedVideoAdWillClose:(id)arg1;
- (void)rewardedVideoAdDidClose:(id)arg1;
- (void)rewardedVideoAdDidClick:(id)arg1;
- (void)rewardedVideoAd:(id)arg1 didFailWithError:(id)arg2;
- (void)rewardedVideoAdDidLoad:(id)arg1;
- (void)loadRewardedAdForAdConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

