//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBMediaViewDelegate-Protocol.h"
#import "FBNativeAdDelegate-Protocol.h"
#import "GADMediatedNativeAd-Protocol.h"
#import "GADMediatedNativeAdDelegate-Protocol.h"
#import "GADMediatedUnifiedNativeAd-Protocol.h"

@class FBAdOptionsView, FBMediaView, FBNativeAd, GADNativeAdImage, GADNativeAdImageAdLoaderOptions, GADNativeAdViewAdOptions, NSArray, NSDecimalNumber, NSDictionary, NSString, UIView;
@protocol GADMAdNetworkAdapter, GADMAdNetworkConnector, OS_dispatch_queue;

@interface GADFBUnifiedNativeAd : NSObject <GADMediatedUnifiedNativeAd, GADMediatedNativeAdDelegate, GADMediatedNativeAd, FBNativeAdDelegate, FBMediaViewDelegate>
{
    id <GADMAdNetworkConnector> _connector;
    id <GADMAdNetworkAdapter> _adapter;
    FBNativeAd *_nativeAd;
    GADNativeAdImageAdLoaderOptions *_nativeAdImageAdLoaderOptions;
    GADNativeAdViewAdOptions *_nativeAdViewAdOptions;
    NSDictionary *_extraAssets;
    NSObject<OS_dispatch_queue> *_lockQueue;
    FBAdOptionsView *_adOptionsView;
    _Bool _impressionLogged;
    FBMediaView *_mediaView;
}

+ (void)mediatedNativeAdDidRecordImpression:(id)arg1;
- (void).cxx_destruct;
- (void)mediaViewDidLoad:(id)arg1;
- (void)mediaViewVideoDidPause:(id)arg1;
- (void)mediaViewVideoDidPlay:(id)arg1;
- (void)mediaViewVideoDidComplete:(id)arg1;
- (void)nativeAdDidFinishHandlingClick:(id)arg1;
- (void)nativeAdDidClick:(id)arg1;
- (void)nativeAd:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeAdWillLogImpression:(id)arg1;
- (void)nativeAdDidLoad:(id)arg1;
- (void)didUntrackView:(id)arg1;
- (void)didRenderInView:(id)arg1 clickableAssetViews:(id)arg2 nonclickableAssetViews:(id)arg3 viewController:(id)arg4;
@property(readonly, nonatomic) _Bool hasVideoContent;
@property(readonly, nonatomic) UIView *adChoicesView;
@property(readonly, nonatomic) UIView *mediaView;
@property(readonly, copy, nonatomic) NSString *price;
@property(readonly, copy, nonatomic) NSString *store;
@property(readonly, copy, nonatomic) NSDecimalNumber *starRating;
@property(readonly, copy, nonatomic) NSString *callToAction;
@property(readonly, nonatomic) GADNativeAdImage *icon;
@property(readonly, copy, nonatomic) NSString *body;
@property(readonly, nonatomic) NSArray *images;
@property(readonly, copy, nonatomic) NSString *advertiser;
@property(readonly, copy, nonatomic) NSString *headline;
@property(readonly, copy, nonatomic) NSDictionary *extraAssets;
- (id)mediatedNativeAdDelegate;
- (void)loadAdOptionsView;
- (void)stopBeingDelegate;
- (void)getNativeAdWithAdTypes:(id)arg1 options:(id)arg2;
- (id)initWithGADMAdNetworkConnector:(id)arg1 adapter:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) double mediaContentAspectRatio;
@property(readonly) Class superclass;

@end

