//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBMediaViewDelegate-Protocol.h"
#import "FBNativeAdDelegate-Protocol.h"
#import "GADMediationNativeAd-Protocol.h"

@class FBAdOptionsView, FBMediaView, FBNativeAd, GADNativeAdImage, NSArray, NSDecimalNumber, NSDictionary, NSString, UIView;
@protocol GADMediationNativeAdEventDelegate, OS_dispatch_queue;

@interface GADFBNativeRenderer : NSObject <GADMediationNativeAd, FBNativeAdDelegate, FBMediaViewDelegate>
{
    CDUnknownBlockType _adLoadCompletionHandler;
    FBNativeAd *_nativeAd;
    id <GADMediationNativeAdEventDelegate> _adEventDelegate;
    NSDictionary *_extraAssets;
    FBAdOptionsView *_adOptionsView;
    _Bool _impressionLogged;
    FBMediaView *_mediaView;
    NSObject<OS_dispatch_queue> *_lockQueue;
    _Bool _isRTBRequest;
}

- (void).cxx_destruct;
- (void)mediaViewDidLoad:(id)arg1;
- (void)mediaView:(id)arg1 videoVolumeDidChange:(float)arg2;
- (void)mediaViewDidExitFullscreen:(id)arg1;
- (void)mediaViewWillEnterFullscreen:(id)arg1;
- (void)mediaViewVideoDidPause:(id)arg1;
- (void)mediaViewVideoDidPlay:(id)arg1;
- (void)mediaViewVideoDidComplete:(id)arg1;
- (void)nativeAdDidDownloadMedia:(id)arg1;
- (void)nativeAdDidFinishHandlingClick:(id)arg1;
- (void)nativeAdWillLogImpression:(id)arg1;
- (void)nativeAd:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeAdDidClick:(id)arg1;
- (void)nativeAdDidLoad:(id)arg1;
@property(readonly, nonatomic) _Bool hasVideoContent;
- (void)didUntrackView:(id)arg1;
- (void)didRenderInView:(id)arg1 clickableAssetViews:(id)arg2 nonclickableAssetViews:(id)arg3 viewController:(id)arg4;
@property(readonly, copy, nonatomic) NSString *store;
@property(readonly, copy, nonatomic) NSDecimalNumber *starRating;
@property(readonly, copy, nonatomic) NSString *price;
@property(readonly, copy, nonatomic) NSString *headline;
@property(readonly, copy, nonatomic) NSDictionary *extraAssets;
@property(readonly, copy, nonatomic) NSString *callToAction;
@property(readonly, nonatomic) GADNativeAdImage *icon;
@property(readonly, nonatomic) UIView *adChoicesView;
@property(readonly, nonatomic) UIView *mediaView;
@property(readonly, nonatomic) NSArray *images;
@property(readonly, copy, nonatomic) NSString *body;
@property(readonly, copy, nonatomic) NSString *advertiser;
- (void)loadAdOptionsView;
- (void)renderNativeAdForAdConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) double mediaContentAspectRatio;
@property(readonly) Class superclass;

@end

