//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GADObserverCollection, NSOperationQueue;
@protocol GADPresenterSource;

@interface GADIntermissionStateMonitor : NSObject
{
    GADObserverCollection *_observers;
    _Bool _idleTimerWasOriginallyDisabled;
    _Bool _statusBarWasOriginallyHidden;
    NSOperationQueue *_deactivationQueue;
    _Bool _applicationBackgroundedDueToAdAction;
    id <GADPresenterSource> _presenterSource;
}

@property(nonatomic) __weak id <GADPresenterSource> presenterSource; // @synthesize presenterSource=_presenterSource;
- (void).cxx_destruct;
- (void)applicationWillEnterForeground;
- (void)setDeactivationQueueSuspended:(_Bool)arg1;
- (void)intermissionWillEnd;
- (void)intermissionDidBegin;
- (id)init;

@end

