//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GADInternalNativeAd;
@protocol GADMediaContentDisplaying;

@interface GADInstreamNativeAd : NSObject
{
    id <GADMediaContentDisplaying> _mediaContent;
    GADInternalNativeAd *_internalNativeAd;
}

@property(readonly, nonatomic) GADInternalNativeAd *internalNativeAd; // @synthesize internalNativeAd=_internalNativeAd;
@property(readonly, nonatomic) id <GADMediaContentDisplaying> mediaContent; // @synthesize mediaContent=_mediaContent;
- (void).cxx_destruct;
- (id)initWithInternalNativeAd:(id)arg1;

@end

