//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADRTBAdapter-Protocol.h"

@class GADFBBannerRenderer, GADFBInterstitialRenderer, GADFBNativeRenderer, GADFBRewardedRenderer, NSString;

@interface GADMediationAdapterFacebook : NSObject <GADRTBAdapter>
{
    GADFBRewardedRenderer *_rewardedAd;
    GADFBNativeRenderer *_native;
    GADFBInterstitialRenderer *_interstitial;
    GADFBBannerRenderer *_banner;
}

+ (CDStruct_2ec95fd7)adSDKVersion;
+ (Class)networkExtrasClass;
+ (CDStruct_2ec95fd7)version;
+ (id)getPlacementIDFromCredentials:(id)arg1;
+ (void)setUpWithConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (void)loadNativeAdForAdConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)loadRewardedAdForAdConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)loadInterstitialForAdConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)loadBannerForAdConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)collectSignalsForRequestParameters:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

