//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface GADSignalConfiguration : NSObject
{
    NSString *_adUnitID;
}

@property(readonly, nonatomic) NSString *adUnitID; // @synthesize adUnitID=_adUnitID;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *adTypes;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithAdUnitID:(id)arg1;

@end

