//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class GCFSDocumentMask, GCFSTransactionOptions, GPBTimestamp, NSData, NSMutableArray, NSString;

@interface GCFSBatchGetDocumentsRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(readonly, nonatomic) int consistencySelectorOneOfCase; // @dynamic consistencySelectorOneOfCase;
@property(copy, nonatomic) NSString *database; // @dynamic database;
@property(retain, nonatomic) NSMutableArray *documentsArray; // @dynamic documentsArray;
@property(readonly, nonatomic) unsigned long long documentsArray_Count; // @dynamic documentsArray_Count;
@property(nonatomic) _Bool hasMask; // @dynamic hasMask;
@property(retain, nonatomic) GCFSDocumentMask *mask; // @dynamic mask;
@property(retain, nonatomic) GCFSTransactionOptions *newTransaction; // @dynamic newTransaction;
@property(retain, nonatomic) GPBTimestamp *readTime; // @dynamic readTime;
@property(copy, nonatomic) NSData *transaction; // @dynamic transaction;

@end

