//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class GCFSDocument, GPBInt32Array;

@interface GCFSDocumentChange : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GCFSDocument *document; // @dynamic document;
@property(nonatomic) _Bool hasDocument; // @dynamic hasDocument;
@property(retain, nonatomic) GPBInt32Array *removedTargetIdsArray; // @dynamic removedTargetIdsArray;
@property(readonly, nonatomic) unsigned long long removedTargetIdsArray_Count; // @dynamic removedTargetIdsArray_Count;
@property(retain, nonatomic) GPBInt32Array *targetIdsArray; // @dynamic targetIdsArray;
@property(readonly, nonatomic) unsigned long long targetIdsArray_Count; // @dynamic targetIdsArray_Count;

@end

