//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class GCFSCursor, GCFSStructuredQuery_Filter, GCFSStructuredQuery_Projection, GPBInt32Value, NSMutableArray;

@interface GCFSStructuredQuery : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GCFSCursor *endAt; // @dynamic endAt;
@property(retain, nonatomic) NSMutableArray *fromArray; // @dynamic fromArray;
@property(readonly, nonatomic) unsigned long long fromArray_Count; // @dynamic fromArray_Count;
@property(nonatomic) _Bool hasEndAt; // @dynamic hasEndAt;
@property(nonatomic) _Bool hasLimit; // @dynamic hasLimit;
@property(nonatomic) _Bool hasSelect; // @dynamic hasSelect;
@property(nonatomic) _Bool hasStartAt; // @dynamic hasStartAt;
@property(nonatomic) _Bool hasWhere; // @dynamic hasWhere;
@property(retain, nonatomic) GPBInt32Value *limit; // @dynamic limit;
@property(nonatomic) int offset; // @dynamic offset;
@property(retain, nonatomic) NSMutableArray *orderByArray; // @dynamic orderByArray;
@property(readonly, nonatomic) unsigned long long orderByArray_Count; // @dynamic orderByArray_Count;
@property(retain, nonatomic) GCFSStructuredQuery_Projection *select; // @dynamic select;
@property(retain, nonatomic) GCFSCursor *startAt; // @dynamic startAt;
@property(retain, nonatomic) GCFSStructuredQuery_Filter *where; // @dynamic where;

@end

