//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class NSString;

@interface GCFSStructuredQuery_CollectionSelector : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool allDescendants; // @dynamic allDescendants;
@property(copy, nonatomic) NSString *collectionId; // @dynamic collectionId;

@end

