//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class NSMutableArray;

@interface GCFSDocumentMask : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *fieldPathsArray; // @dynamic fieldPathsArray;
@property(readonly, nonatomic) unsigned long long fieldPathsArray_Count; // @dynamic fieldPathsArray_Count;

@end

