//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class GCFSDocumentChange, GCFSDocumentDelete, GCFSDocumentRemove, GCFSExistenceFilter, GCFSTargetChange;

@interface GCFSListenResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GCFSDocumentChange *documentChange; // @dynamic documentChange;
@property(retain, nonatomic) GCFSDocumentDelete *documentDelete; // @dynamic documentDelete;
@property(retain, nonatomic) GCFSDocumentRemove *documentRemove; // @dynamic documentRemove;
@property(retain, nonatomic) GCFSExistenceFilter *filter; // @dynamic filter;
@property(readonly, nonatomic) int responseTypeOneOfCase; // @dynamic responseTypeOneOfCase;
@property(retain, nonatomic) GCFSTargetChange *targetChange; // @dynamic targetChange;

@end

