//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class GCFSDocument, GCFSDocumentMask, NSString;

@interface GCFSCreateDocumentRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *collectionId; // @dynamic collectionId;
@property(retain, nonatomic) GCFSDocument *document; // @dynamic document;
@property(copy, nonatomic) NSString *documentId; // @dynamic documentId;
@property(nonatomic) _Bool hasDocument; // @dynamic hasDocument;
@property(nonatomic) _Bool hasMask; // @dynamic hasMask;
@property(retain, nonatomic) GCFSDocumentMask *mask; // @dynamic mask;
@property(copy, nonatomic) NSString *parent; // @dynamic parent;

@end

