//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class GCFSArrayValue, GCFSMapValue, GPBTimestamp, GTPLatLng, NSData, NSString;

@interface GCFSValue : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GCFSArrayValue *arrayValue; // @dynamic arrayValue;
@property(nonatomic) _Bool booleanValue; // @dynamic booleanValue;
@property(copy, nonatomic) NSData *bytesValue; // @dynamic bytesValue;
@property(nonatomic) double doubleValue; // @dynamic doubleValue;
@property(retain, nonatomic) GTPLatLng *geoPointValue; // @dynamic geoPointValue;
@property(nonatomic) long long integerValue; // @dynamic integerValue;
@property(retain, nonatomic) GCFSMapValue *mapValue; // @dynamic mapValue;
@property(nonatomic) int nullValue; // @dynamic nullValue;
@property(copy, nonatomic) NSString *referenceValue; // @dynamic referenceValue;
@property(copy, nonatomic) NSString *stringValue; // @dynamic stringValue;
@property(retain, nonatomic) GPBTimestamp *timestampValue; // @dynamic timestampValue;
@property(readonly, nonatomic) int valueTypeOneOfCase; // @dynamic valueTypeOneOfCase;

@end

