//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class GPBInt32Array, GPBTimestamp, NSData, RPCStatus;

@interface GCFSTargetChange : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) RPCStatus *cause; // @dynamic cause;
@property(nonatomic) _Bool hasCause; // @dynamic hasCause;
@property(nonatomic) _Bool hasReadTime; // @dynamic hasReadTime;
@property(retain, nonatomic) GPBTimestamp *readTime; // @dynamic readTime;
@property(copy, nonatomic) NSData *resumeToken; // @dynamic resumeToken;
@property(nonatomic) int targetChangeType; // @dynamic targetChangeType;
@property(retain, nonatomic) GPBInt32Array *targetIdsArray; // @dynamic targetIdsArray;
@property(readonly, nonatomic) unsigned long long targetIdsArray_Count; // @dynamic targetIdsArray_Count;

@end

