//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class GCFSStructuredQuery, GCFSTransactionOptions, GPBTimestamp, NSData, NSString;

@interface GCFSRunQueryRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(readonly, nonatomic) int consistencySelectorOneOfCase; // @dynamic consistencySelectorOneOfCase;
@property(retain, nonatomic) GCFSTransactionOptions *newTransaction; // @dynamic newTransaction;
@property(copy, nonatomic) NSString *parent; // @dynamic parent;
@property(readonly, nonatomic) int queryTypeOneOfCase; // @dynamic queryTypeOneOfCase;
@property(retain, nonatomic) GPBTimestamp *readTime; // @dynamic readTime;
@property(retain, nonatomic) GCFSStructuredQuery *structuredQuery; // @dynamic structuredQuery;
@property(copy, nonatomic) NSData *transaction; // @dynamic transaction;

@end

