//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Protobuf/GPBMessage.h>

@class GCFSArrayValue, GCFSValue, NSString;

@interface GCFSDocumentTransform_FieldTransform : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GCFSArrayValue *appendMissingElements; // @dynamic appendMissingElements;
@property(copy, nonatomic) NSString *fieldPath; // @dynamic fieldPath;
@property(retain, nonatomic) GCFSValue *increment; // @dynamic increment;
@property(retain, nonatomic) GCFSValue *maximum; // @dynamic maximum;
@property(retain, nonatomic) GCFSValue *minimum; // @dynamic minimum;
@property(retain, nonatomic) GCFSArrayValue *removeAllFromArray_p; // @dynamic removeAllFromArray_p;
@property(nonatomic) int setToServerValue; // @dynamic setToServerValue;
@property(readonly, nonatomic) int transformTypeOneOfCase; // @dynamic transformTypeOneOfCase;

@end

