//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTUploader-Protocol.h"

@class GDTClock, GDTUploadPackage, NSString, NSURL, NSURLSession, NSURLSessionUploadTask;
@protocol OS_dispatch_queue;

@interface GDTCCTUploader : NSObject <GDTUploader>
{
    _Bool _runningInBackground;
    NSObject<OS_dispatch_queue> *_uploaderQueue;
    NSURL *_serverURL;
    NSURLSession *_uploaderSession;
    NSURLSessionUploadTask *_currentTask;
    GDTUploadPackage *_currentUploadPackage;
    GDTClock *_nextUploadTime;
}

+ (id)sharedInstance;
+ (void)load;
@property(nonatomic) _Bool runningInBackground; // @synthesize runningInBackground=_runningInBackground;
@property(retain, nonatomic) GDTClock *nextUploadTime; // @synthesize nextUploadTime=_nextUploadTime;
@property(retain, nonatomic) GDTUploadPackage *currentUploadPackage; // @synthesize currentUploadPackage=_currentUploadPackage;
@property(retain, nonatomic) NSURLSessionUploadTask *currentTask; // @synthesize currentTask=_currentTask;
@property(readonly, nonatomic) NSURLSession *uploaderSession; // @synthesize uploaderSession=_uploaderSession;
@property(retain, nonatomic) NSURL *serverURL; // @synthesize serverURL=_serverURL;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *uploaderQueue; // @synthesize uploaderQueue=_uploaderQueue;
- (void).cxx_destruct;
- (void)appWillTerminate:(id)arg1;
- (void)appWillForeground:(id)arg1;
- (void)appWillBackground:(id)arg1;
- (void)packageExpired:(id)arg1;
- (id)constructRequestProtoFromPackage:(id)arg1;
- (_Bool)readyToUploadWithConditions:(long long)arg1;
- (void)uploadPackage:(id)arg1;
- (id)defaultServerURL;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

