//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (FBAdUtility)
- (void)setFloat:(float)arg1 forKey:(id)arg2;
- (void)setNSTimeInterval:(double)arg1 forKey:(id)arg2;
- (void)setObjectIfNotExists:(id)arg1 forKey:(id)arg2;
- (void)setNullStringIfNullCharPointer:(const char *)arg1 forKey:(id)arg2;
- (void)setNullStringIfNilObject:(id)arg1 forKey:(id)arg2;
- (void)setNonNilObject:(id)arg1 forKey:(id)arg2;
@end

