//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class FIRStorageDownloadTask;

@interface UIImageView (FirebaseStorage)
@property(readonly, nonatomic) FIRStorageDownloadTask *sd_currentDownloadTask;
- (void)sd_setImageWithStorageReference:(id)arg1 maxImageSize:(unsigned long long)arg2 placeholderImage:(id)arg3 options:(unsigned long long)arg4 context:(struct NSDictionary *)arg5 progress:(CDUnknownBlockType)arg6 completion:(CDUnknownBlockType)arg7;
- (void)sd_setImageWithStorageReference:(id)arg1 maxImageSize:(unsigned long long)arg2 placeholderImage:(id)arg3 options:(unsigned long long)arg4 progress:(CDUnknownBlockType)arg5 completion:(CDUnknownBlockType)arg6;
- (void)sd_setImageWithStorageReference:(id)arg1 maxImageSize:(unsigned long long)arg2 placeholderImage:(id)arg3 options:(unsigned long long)arg4 completion:(CDUnknownBlockType)arg5;
- (void)sd_setImageWithStorageReference:(id)arg1 maxImageSize:(unsigned long long)arg2 placeholderImage:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)sd_setImageWithStorageReference:(id)arg1 placeholderImage:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)sd_setImageWithStorageReference:(id)arg1 placeholderImage:(id)arg2;
- (void)sd_setImageWithStorageReference:(id)arg1;
@end

